namespace powerFlexBackup.cipdevice.PortCards
{
    /// <summary>
    /// DeviceLogix Embedded Controller
    ///
    /// PowerFlex 750 Series built-in DeviceLogix controller.
    /// Typically found on Port 14 of PF753/PF755 drives.
    ///
    /// Parameters include digital/analog I/O, DIP switch setpoints,
    /// REAL/DINT setpoints, and boolean setpoints for DeviceLogix programs.
    /// </summary>
    public class PF750_PortCard_DeviceLogix : PowerFlex750PortCard
    {
        public override ushort[] ProductCodes => [33184];
        public override string ProductName => "DeviceLogix";
        public override int ClassID => 0x9F;

        protected override string parameterListJSON => @"[
            { 'number': '1', 'name': 'DLX Out 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '2', 'name': 'DLX Out 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '3', 'name': 'DLX Out 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '4', 'name': 'DLX Out 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '5', 'name': 'DLX Out 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '6', 'name': 'DLX Out 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '7', 'name': 'DLX Out 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '8', 'name': 'DLX Out 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '9', 'name': 'DLX Out 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '10', 'name': 'DLX Out 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '11', 'name': 'DLX Out 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '12', 'name': 'DLX Out 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '13', 'name': 'DLX Out 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '14', 'name': 'DLX Out 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '15', 'name': 'DLX Out 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '16', 'name': 'DLX Out 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '17', 'name': 'DLX In 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '18', 'name': 'DLX In 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '19', 'name': 'DLX In 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '20', 'name': 'DLX In 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '21', 'name': 'DLX In 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '22', 'name': 'DLX In 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '23', 'name': 'DLX In 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '24', 'name': 'DLX In 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '25', 'name': 'DLX In 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '26', 'name': 'DLX In 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '27', 'name': 'DLX In 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '28', 'name': 'DLX In 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '29', 'name': 'DLX In 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '30', 'name': 'DLX In 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '31', 'name': 'DLX In 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '32', 'name': 'DLX In 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '33', 'name': 'DLX DIP 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '34', 'name': 'DLX DIP 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '35', 'name': 'DLX DIP 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '36', 'name': 'DLX DIP 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '37', 'name': 'DLX DIP 5', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '38', 'name': 'DLX DIP 6', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '39', 'name': 'DLX DIP 7', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '40', 'name': 'DLX DIP 8', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '41', 'name': 'DLX DIP 9', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '42', 'name': 'DLX DIP 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '43', 'name': 'DLX DIP 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '44', 'name': 'DLX DIP 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '45', 'name': 'DLX DIP 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '46', 'name': 'DLX DIP 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '47', 'name': 'DLX DIP 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '48', 'name': 'DLX DIP 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '49', 'name': 'DLX DigIn Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '50', 'name': 'DLX DigOut Sts', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '51', 'name': 'DLX DigOut Sts2', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '52', 'name': 'DLX Prog Cond', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '53', 'name': 'DLX Operation', 'defaultValue': '5', 'record': 'true', 'type': 'yA==' },
            { 'number': '54', 'name': 'DLX Real SP1', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '55', 'name': 'DLX Real SP2', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '56', 'name': 'DLX Real SP3', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '57', 'name': 'DLX Real SP4', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '58', 'name': 'DLX Real SP5', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '59', 'name': 'DLX Real SP6', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '60', 'name': 'DLX Real SP7', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '61', 'name': 'DLX Real SP8', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '62', 'name': 'DLX Real SP9', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '63', 'name': 'DLX Real SP10', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '64', 'name': 'DLX Real SP11', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '65', 'name': 'DLX Real SP12', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '66', 'name': 'DLX Real SP13', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '67', 'name': 'DLX Real SP14', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '68', 'name': 'DLX Real SP15', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '69', 'name': 'DLX Real SP16', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '70', 'name': 'DLX DINT SP1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '71', 'name': 'DLX DINT SP2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '72', 'name': 'DLX DINT SP3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '73', 'name': 'DLX DINT SP4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '74', 'name': 'DLX DINT SP5', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '75', 'name': 'DLX DINT SP6', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '76', 'name': 'DLX DINT SP7', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '77', 'name': 'DLX DINT SP8', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '78', 'name': 'DLX Bool SP1', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '79', 'name': 'DLX Bool SP2', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '80', 'name': 'DLX Bool SP3', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '81', 'name': 'DLX Bool SP4', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '82', 'name': 'DLX Real In SP1', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '83', 'name': 'DLX Real In SP2', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '84', 'name': 'DLX Real In SP3', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '85', 'name': 'DLX Real In SP4', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '86', 'name': 'DLX Real In SP5', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '87', 'name': 'DLX Real In SP6', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '88', 'name': 'DLX Real In SP7', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '89', 'name': 'DLX Real In SP8', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '90', 'name': 'DLX Real Out SP1', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '91', 'name': 'DLX Real Out SP2', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '92', 'name': 'DLX Real Out SP3', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '93', 'name': 'DLX Real Out SP4', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '94', 'name': 'DLX Real Out SP5', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '95', 'name': 'DLX Real Out SP6', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '96', 'name': 'DLX Real Out SP7', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '97', 'name': 'DLX Real Out SP8', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '98', 'name': 'DLX DINT In SP1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '99', 'name': 'DLX DINT In SP2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '100', 'name': 'DLX DINT In SP3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '101', 'name': 'DLX DINT In SP4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '102', 'name': 'DLX DINT Out SP1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '103', 'name': 'DLX DINT Out SP2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '104', 'name': 'DLX DINT Out SP3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '105', 'name': 'DLX DINT Out SP4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' }
        ]";
    }
}
