namespace powerFlexBackup.cipdevice.PortCards
{
    /// <summary>
    /// PowerFlex 753 Main Drive Controller
    ///
    /// PowerFlex 750 Series main drive at Port 0.
    /// ProductCode 1168 identifies the PowerFlex 753.
    ///
    /// 665 parameters (507 writable, 158 read-only).
    /// Types: yg== (0xCA REAL), yA== (0xC8 DINT), 0g== (0xD2 DWORD), 0w== (0xD3 LWORD)
    /// </summary>
    public class PF750_PortCard_PowerFlex753 : PowerFlex750PortCard
    {
        public override ushort[] ProductCodes => [1168];
        public override string ProductName => "PowerFlex 753";
        public override int ClassID => 0x9F;

        protected override string hostParameterListJSON => @"[
            { 'number': '1', 'name': 'Output Frequency', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '2', 'name': 'Commanded SpdRef', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '3', 'name': 'Mtr Vel Fdbk', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '4', 'name': 'Commanded Trq', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '5', 'name': 'Torque Cur Fdbk', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '6', 'name': 'Flux Cur Fdbk', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '7', 'name': 'Output Current', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '8', 'name': 'Output Voltage', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '9', 'name': 'Output Power', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '10', 'name': 'Output Powr Fctr', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '11', 'name': 'DC Bus Volts', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '12', 'name': 'DC Bus Memory', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '13', 'name': 'Elapsed MWH', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '14', 'name': 'Elapsed kWH', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '15', 'name': 'Elapsed Run Time', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '16', 'name': 'Elpsd Mtr MWHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '17', 'name': 'Elpsd Rgn MWHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '18', 'name': 'Elpsd Mtr kWHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '19', 'name': 'Elpsd Rgn kWHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '20', 'name': 'Rated Volts', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '21', 'name': 'Rated Amps', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '22', 'name': 'Rated kW', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '25', 'name': 'Motor NP Volts', 'defaultValue': '460', 'record': 'true', 'type': 'yg==' },
            { 'number': '26', 'name': 'Motor NP Amps', 'defaultValue': '59.1', 'record': 'true', 'type': 'yg==' },
            { 'number': '27', 'name': 'Motor NP Hertz', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '28', 'name': 'Motor NP RPM', 'defaultValue': '1775', 'record': 'true', 'type': 'yg==' },
            { 'number': '29', 'name': 'Mtr NP Pwr Units', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '30', 'name': 'Motor NP Power', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '31', 'name': 'Motor Poles', 'defaultValue': '4', 'record': 'true', 'type': 'yA==' },
            { 'number': '35', 'name': 'Motor Ctrl Mode', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '36', 'name': 'Maximum Voltage', 'defaultValue': '460', 'record': 'true', 'type': 'yg==' },
            { 'number': '37', 'name': 'Maximum Freq', 'defaultValue': '130', 'record': 'true', 'type': 'yg==' },
            { 'number': '38', 'name': 'PWM Frequency', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '39', 'name': 'PWM Trans Freq', 'defaultValue': '2.2', 'record': 'true', 'type': 'yg==' },
            { 'number': '40', 'name': 'Mtr Options Cfg', 'defaultValue': '00000000000000001001100011100111', 'record': 'true', 'type': '0w==' },
            { 'number': '41', 'name': 'Common Mode Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '43', 'name': 'Flux Up Enable', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '44', 'name': 'Flux Up Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '60', 'name': 'Start Acc Boost', 'defaultValue': '5.4', 'record': 'true', 'type': 'yg==' },
            { 'number': '61', 'name': 'Run Boost', 'defaultValue': '5.4', 'record': 'true', 'type': 'yg==' },
            { 'number': '62', 'name': 'Break Voltage', 'defaultValue': '115', 'record': 'true', 'type': 'yg==' },
            { 'number': '63', 'name': 'Break Frequency', 'defaultValue': '15', 'record': 'true', 'type': 'yg==' },
            { 'number': '65', 'name': 'VHz Curve', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '70', 'name': 'Autotune', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '71', 'name': 'Autotune Torque', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '73', 'name': 'IR Voltage Drop', 'defaultValue': '5.4', 'record': 'true', 'type': 'yg==' },
            { 'number': '74', 'name': 'Ixo Voltage Drop', 'defaultValue': '115', 'record': 'true', 'type': 'yg==' },
            { 'number': '75', 'name': 'Flux Current Ref', 'defaultValue': '22.75', 'record': 'true', 'type': 'yg==' },
            { 'number': '76', 'name': 'Total Inertia', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '77', 'name': 'Inertia Test Lmt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '150', 'name': 'Digital In Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '155', 'name': 'DI Enable', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '156', 'name': 'DI Clear Fault', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '157', 'name': 'DI Aux Fault', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '158', 'name': 'DI Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '159', 'name': 'DI Cur Lmt Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '160', 'name': 'DI Coast Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '161', 'name': 'DI Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '162', 'name': 'DI Fwd Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '163', 'name': 'DI Run', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '164', 'name': 'DI Run Forward', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '165', 'name': 'DI Run Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '166', 'name': 'DI Jog 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '167', 'name': 'DI Jog 1 Forward', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '168', 'name': 'DI Jog 1 Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '169', 'name': 'DI Jog 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '170', 'name': 'DI Jog 2 Forward', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '171', 'name': 'DI Jog 2 Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '172', 'name': 'DI Manual Ctrl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '173', 'name': 'DI Speed Sel 0', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '174', 'name': 'DI Speed Sel 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '175', 'name': 'DI Speed Sel 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '176', 'name': 'DI HOA Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '177', 'name': 'DI MOP Inc', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '178', 'name': 'DI MOP Dec', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '179', 'name': 'DI Accel 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '180', 'name': 'DI Decel 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '181', 'name': 'DI SpTqPs Sel 0', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '182', 'name': 'DI SpTqPs Sel 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '185', 'name': 'DI Stop Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '186', 'name': 'DI BusReg Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '187', 'name': 'DI PwrLoss ModeB', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '188', 'name': 'DI Pwr Loss', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '189', 'name': 'DI Precharge', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '190', 'name': 'DI Prchrg Seal', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '191', 'name': 'DI PID Enable', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '192', 'name': 'DI PID Hold', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '193', 'name': 'DI PID Reset', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '194', 'name': 'DI PID Invert', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '195', 'name': 'DI Torque StptA', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '196', 'name': 'DI Fwd End Limit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '197', 'name': 'DI Fwd Dec Limit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '198', 'name': 'DI Rev End Limit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '199', 'name': 'DI Rev Dec Limit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '200', 'name': 'DI PHdwr OvrTrvl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '201', 'name': 'DI NHdwr OvrTrvl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '220', 'name': 'Digital In Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '222', 'name': 'Dig In Filt Mask', 'defaultValue': '0000000000000110', 'record': 'true', 'type': '0g==' },
            { 'number': '223', 'name': 'Dig In Filt', 'defaultValue': '4', 'record': 'true', 'type': 'yA==' },
            { 'number': '225', 'name': 'Dig Out Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '226', 'name': 'Dig Out Invert', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '227', 'name': 'Dig Out Setpoint', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '230', 'name': 'RO0 Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '231', 'name': 'RO0 Level Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '232', 'name': 'RO0 Level', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '233', 'name': 'RO0 Level CmpSts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '234', 'name': 'RO0 On Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '235', 'name': 'RO0 Off Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '240', 'name': 'TO0 Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '241', 'name': 'TO0 Level Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '242', 'name': 'TO0 Level', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '243', 'name': 'TO0 Level CmpSts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '244', 'name': 'TO0 On Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '245', 'name': 'TO0 Off Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '250', 'name': 'PTC Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '251', 'name': 'PTC Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '255', 'name': 'Anlg In Type', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '256', 'name': 'Anlg In Sqrt', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '257', 'name': 'Anlg In Loss Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '260', 'name': 'Anlg In0 Value', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '261', 'name': 'Anlg In0 Hi', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '262', 'name': 'Anlg In0 Lo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '263', 'name': 'Anlg In0 LssActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '264', 'name': 'Anlg In0 Raw Val', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '265', 'name': 'Anlg In0 Filt Gn', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '266', 'name': 'Anlg In0 Filt BW', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '270', 'name': 'Anlg Out Type', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '271', 'name': 'Anlg Out Abs', 'defaultValue': '0000000000000001', 'record': 'true', 'type': '0g==' },
            { 'number': '275', 'name': 'Anlg Out0 Sel', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '276', 'name': 'Anlg Out0 Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '277', 'name': 'Anlg Out0 Data', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '278', 'name': 'Anlg Out0 DataHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '279', 'name': 'Anlg Out0 DataLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '280', 'name': 'Anlg Out0 Hi', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '281', 'name': 'Anlg Out0 Lo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '282', 'name': 'Anlg Out0 Val', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '285', 'name': 'RO PredMaint Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '286', 'name': 'RO0 Load Type', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '287', 'name': 'RO0 Load Amps', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '288', 'name': 'RO0 TotalLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '289', 'name': 'RO0 ElapsedLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '290', 'name': 'RO0 RemainLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '291', 'name': 'RO0 LifeEvntLvl', 'defaultValue': '80', 'record': 'true', 'type': 'yg==' },
            { 'number': '292', 'name': 'RO0 LifeEvntActn', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '300', 'name': 'Speed Units', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '301', 'name': 'Access Level', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '302', 'name': 'Language', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '303', 'name': 'Fdbk Filter Cfg', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '305', 'name': 'Voltage Class', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '306', 'name': 'Duty Rating', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '308', 'name': 'Direction Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '309', 'name': 'SpdTrqPsn Mode A', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '310', 'name': 'SpdTrqPsn Mode B', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '311', 'name': 'SpdTrqPsn Mode C', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '312', 'name': 'SpdTrqPsn Mode D', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '313', 'name': 'Actv SpTqPs Mode', 'defaultValue': '1', 'record': 'false', 'type': 'yA==' },
            { 'number': '314', 'name': 'SLAT Err Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '315', 'name': 'SLAT Dwell Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '321', 'name': 'Prchrg Control', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '322', 'name': 'Prchrg Delay', 'defaultValue': '0.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '323', 'name': 'Prchrg Err Cfg', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '324', 'name': 'Logic Mask', 'defaultValue': '0100001001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '325', 'name': 'Auto Mask', 'defaultValue': '0100000001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '326', 'name': 'Manual Cmd Mask', 'defaultValue': '0100000001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '327', 'name': 'Manual Ref Mask', 'defaultValue': '0000000000001111', 'record': 'true', 'type': '0g==' },
            { 'number': '328', 'name': 'Alt Man Ref Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '329', 'name': 'Alt Man Ref AnHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '330', 'name': 'Alt Man Ref AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '331', 'name': 'Manual Preload', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '336', 'name': 'Reset Meters', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '338', 'name': 'AutoClrFlt Tries', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '339', 'name': 'AutoClrFlt Delay', 'defaultValue': '30', 'record': 'true', 'type': 'yg==' },
            { 'number': '340', 'name': 'AutoClrCntrDelay', 'defaultValue': '300', 'record': 'true', 'type': 'yg==' },
            { 'number': '343', 'name': 'Rstrt Cntr Delay', 'defaultValue': '300', 'record': 'true', 'type': 'yg==' },
            { 'number': '345', 'name': 'Start At PowerUp', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '346', 'name': 'PowerUp Delay', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '347', 'name': 'Auto Retry Fault', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '348', 'name': 'Auto Rstrt Tries', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '349', 'name': 'Auto Rstrt Delay', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '350', 'name': 'Sleep Wake Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '351', 'name': 'SleepWake RefSel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '352', 'name': 'Sleep Level', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '353', 'name': 'Sleep Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '354', 'name': 'Wake Level', 'defaultValue': '6', 'record': 'true', 'type': 'yg==' },
            { 'number': '355', 'name': 'Wake Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '356', 'name': 'FlyingStart Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '365', 'name': 'FS Brk Lvl', 'defaultValue': '45.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '370', 'name': 'Stop Mode A', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '371', 'name': 'Stop Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '372', 'name': 'Bus Reg Mode A', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '373', 'name': 'Bus Reg Mode B', 'defaultValue': '4', 'record': 'true', 'type': 'yA==' },
            { 'number': '374', 'name': 'Bus Reg Lvl Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '375', 'name': 'Bus Reg Level', 'defaultValue': '750.076', 'record': 'true', 'type': 'yg==' },
            { 'number': '382', 'name': 'DB Resistor Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '383', 'name': 'DB Ext Ohms', 'defaultValue': '15.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '384', 'name': 'DB Ext Watts', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '385', 'name': 'DB ExtPulseWatts', 'defaultValue': '2000', 'record': 'true', 'type': 'yg==' },
            { 'number': '388', 'name': 'Flux Braking En', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '389', 'name': 'Flux Braking Lmt', 'defaultValue': '125', 'record': 'true', 'type': 'yg==' },
            { 'number': '392', 'name': 'Stop Dwell Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '393', 'name': 'DC Brake Lvl Sel', 'defaultValue': '394', 'record': 'true', 'type': 'yA==' },
            { 'number': '394', 'name': 'DC Brake Level', 'defaultValue': '65', 'record': 'true', 'type': 'yg==' },
            { 'number': '395', 'name': 'DC Brake Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '402', 'name': 'Brake Off Adj 1', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '403', 'name': 'Brake Off Adj 2', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '409', 'name': 'Dec Inhibit Actn', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '410', 'name': 'Motor OL Actn', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '411', 'name': 'Mtr OL at Pwr Up', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '412', 'name': 'Mtr OL Alarm Lvl', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '413', 'name': 'Mtr OL Factor', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '414', 'name': 'Mtr OL Hertz', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '415', 'name': 'Mtr OL Reset Lvl', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '416', 'name': 'MtrOL Reset Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '418', 'name': 'Mtr OL Counts', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '419', 'name': 'Mtr OL Trip Time', 'defaultValue': '99999', 'record': 'false', 'type': 'yA==' },
            { 'number': '420', 'name': 'Drive OL Mode', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '421', 'name': 'Current Lmt Sel', 'defaultValue': '422', 'record': 'true', 'type': 'yA==' },
            { 'number': '422', 'name': 'Current Limit 1', 'defaultValue': '97.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '423', 'name': 'Current Limit 2', 'defaultValue': '97.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '424', 'name': 'Active Cur Lmt', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '425', 'name': 'Current Rate Lmt', 'defaultValue': '400', 'record': 'true', 'type': 'yg==' },
            { 'number': '426', 'name': 'Regen Power Lmt', 'defaultValue': '-50', 'record': 'true', 'type': 'yg==' },
            { 'number': '427', 'name': 'Motor Power Lmt', 'defaultValue': '200', 'record': 'true', 'type': 'yg==' },
            { 'number': '434', 'name': 'Shear Pin Cfg', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '435', 'name': 'Shear Pin 1 Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '436', 'name': 'Shear Pin1 Level', 'defaultValue': '65', 'record': 'true', 'type': 'yg==' },
            { 'number': '437', 'name': 'Shear Pin 1 Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '438', 'name': 'Shear Pin 2 Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '439', 'name': 'Shear Pin2 Level', 'defaultValue': '65', 'record': 'true', 'type': 'yg==' },
            { 'number': '440', 'name': 'Shear Pin 2 Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '441', 'name': 'Load Loss Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '442', 'name': 'Load Loss Level', 'defaultValue': '200', 'record': 'true', 'type': 'yg==' },
            { 'number': '443', 'name': 'Load Loss Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '444', 'name': 'OutPhaseLossActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '445', 'name': 'Out PhaseLossLvl', 'defaultValue': '200', 'record': 'true', 'type': 'yA==' },
            { 'number': '449', 'name': 'Power Loss Actn', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '450', 'name': 'Pwr Loss Mode A', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '451', 'name': 'Pwr Loss A Level', 'defaultValue': '180', 'record': 'true', 'type': 'yg==' },
            { 'number': '452', 'name': 'Pwr Loss A Time', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '453', 'name': 'Pwr Loss Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '454', 'name': 'Pwr Loss B Level', 'defaultValue': '180', 'record': 'true', 'type': 'yg==' },
            { 'number': '455', 'name': 'Pwr Loss B Time', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '460', 'name': 'UnderVltg Action', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '461', 'name': 'UnderVltg Level', 'defaultValue': '300', 'record': 'true', 'type': 'yg==' },
            { 'number': '462', 'name': 'InPhase LossActn', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '463', 'name': 'InPhase Loss Lvl', 'defaultValue': '325', 'record': 'true', 'type': 'yA==' },
            { 'number': '464', 'name': 'DC Bus Mem Reset', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '466', 'name': 'Ground Warn Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '467', 'name': 'Ground Warn Lvl', 'defaultValue': '4', 'record': 'true', 'type': 'yg==' },
            { 'number': '469', 'name': 'PredMaint Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '470', 'name': 'PredMaintAmbTemp', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '471', 'name': 'PredMaint Rst En', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '472', 'name': 'PredMaint Reset', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '488', 'name': 'HSFan Derate', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '489', 'name': 'HSFan TotalLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '490', 'name': 'HSFan ElpsdLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '491', 'name': 'HSFan RemainLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '492', 'name': 'HSFan EventLevel', 'defaultValue': '80', 'record': 'true', 'type': 'yg==' },
            { 'number': '493', 'name': 'HSFan EventActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '494', 'name': 'HSFan ResetLog', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '495', 'name': 'InFan Derate', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '496', 'name': 'InFan TotalLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '497', 'name': 'InFan ElpsdLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '498', 'name': 'InFan RemainLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '499', 'name': 'InFan EventLevel', 'defaultValue': '80', 'record': 'true', 'type': 'yg==' },
            { 'number': '500', 'name': 'InFan EventActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '501', 'name': 'InFan ResetLog', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '502', 'name': 'MtrBrngTotalLife', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '503', 'name': 'MtrBrngElpsdLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '504', 'name': 'MtrBrngRemainLif', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '505', 'name': 'MtrBrngEventLvl', 'defaultValue': '80', 'record': 'true', 'type': 'yg==' },
            { 'number': '506', 'name': 'MtrBrngEventActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '507', 'name': 'MtrBrng ResetLog', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '508', 'name': 'MtrLubeElpsdHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '509', 'name': 'MtrLubeEventLvl', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '510', 'name': 'MtrLubeEventActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '511', 'name': 'MchBrngTotalLife', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '512', 'name': 'MchBrngElpsdLife', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '513', 'name': 'MchBrngRemainLif', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '514', 'name': 'MchBrngEventLvl', 'defaultValue': '80', 'record': 'true', 'type': 'yg==' },
            { 'number': '515', 'name': 'MchBrngEventActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '516', 'name': 'MchBrngResetLog', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '517', 'name': 'MchLubeElpsdHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '518', 'name': 'MchLube EventLvl', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '519', 'name': 'MchLubeEventActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '520', 'name': 'Max Fwd Speed', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '521', 'name': 'Max Rev Speed', 'defaultValue': '-60', 'record': 'true', 'type': 'yg==' },
            { 'number': '522', 'name': 'Min Fwd Speed', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '523', 'name': 'Min Rev Speed', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '524', 'name': 'Overspeed Limit', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '525', 'name': 'Zero Speed Limit', 'defaultValue': '0.06', 'record': 'true', 'type': 'yg==' },
            { 'number': '526', 'name': 'Skip Speed 1', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '527', 'name': 'Skip Speed 2', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '528', 'name': 'Skip Speed 3', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '529', 'name': 'Skip Speed Band', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '535', 'name': 'Accel Time 1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '536', 'name': 'Accel Time 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '537', 'name': 'Decel Time 1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '538', 'name': 'Decel Time 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '539', 'name': 'Jog Acc Dec Time', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '540', 'name': 'S Curve Accel', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '541', 'name': 'S Curve Decel', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '545', 'name': 'Spd Ref A Sel', 'defaultValue': '871', 'record': 'true', 'type': 'yA==' },
            { 'number': '546', 'name': 'Spd Ref A Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '547', 'name': 'Spd Ref A AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '548', 'name': 'Spd Ref A AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '549', 'name': 'Spd Ref A Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '550', 'name': 'Spd Ref B Sel', 'defaultValue': '551', 'record': 'true', 'type': 'yA==' },
            { 'number': '551', 'name': 'Spd Ref B Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '552', 'name': 'Spd Ref B AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '553', 'name': 'Spd Ref B AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '554', 'name': 'Spd Ref B Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '555', 'name': 'Spd Ref Scale', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '556', 'name': 'Jog Speed 1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '557', 'name': 'Jog Speed 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '558', 'name': 'MOP Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '559', 'name': 'Save MOP Ref', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '560', 'name': 'MOP Rate', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '561', 'name': 'MOP High Limit', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '562', 'name': 'MOP Low Limit', 'defaultValue': '-100', 'record': 'true', 'type': 'yg==' },
            { 'number': '563', 'name': 'DI ManRef Sel', 'defaultValue': '872', 'record': 'true', 'type': 'yA==' },
            { 'number': '564', 'name': 'DI ManRef AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '565', 'name': 'DI ManRef AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '566', 'name': 'MOP Init Select', 'defaultValue': '567', 'record': 'true', 'type': 'yA==' },
            { 'number': '567', 'name': 'MOP Init Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '571', 'name': 'Preset Speed 1', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '572', 'name': 'Preset Speed 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '573', 'name': 'Preset Speed 3', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '574', 'name': 'Preset Speed 4', 'defaultValue': '30', 'record': 'true', 'type': 'yg==' },
            { 'number': '575', 'name': 'Preset Speed 5', 'defaultValue': '40', 'record': 'true', 'type': 'yg==' },
            { 'number': '576', 'name': 'Preset Speed 6', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '577', 'name': 'Preset Speed 7', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '600', 'name': 'Trim Ref A Sel', 'defaultValue': '601', 'record': 'true', 'type': 'yA==' },
            { 'number': '601', 'name': 'Trim Ref A Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '602', 'name': 'Trim RefA AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '603', 'name': 'Trim RefA AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '604', 'name': 'Trim Ref B Sel', 'defaultValue': '605', 'record': 'true', 'type': 'yA==' },
            { 'number': '605', 'name': 'Trim Ref B Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '606', 'name': 'Trim RefB AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '607', 'name': 'Trim RefB AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '608', 'name': 'TrmPct RefA Sel', 'defaultValue': '609', 'record': 'true', 'type': 'yA==' },
            { 'number': '609', 'name': 'TrmPct RefA Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '610', 'name': 'TrmPct RefA AnHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '611', 'name': 'TrmPct RefA AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '612', 'name': 'TrmPct RefB Sel', 'defaultValue': '613', 'record': 'true', 'type': 'yA==' },
            { 'number': '613', 'name': 'TrmPct RefB Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '614', 'name': 'TrmPct RefB AnHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '615', 'name': 'TrmPct RefB AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '620', 'name': 'Droop RPM at FLA', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '621', 'name': 'Slip RPM at FLA', 'defaultValue': '-1740', 'record': 'true', 'type': 'yg==' },
            { 'number': '622', 'name': 'Slip Comp BW', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '635', 'name': 'Spd Options Ctrl', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '636', 'name': 'Speed Reg BW', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '640', 'name': 'Filtered SpdFdbk', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '641', 'name': 'Speed Error', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '645', 'name': 'Speed Reg Kp', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '646', 'name': 'Speed Reg Max Kp', 'defaultValue': '3000', 'record': 'true', 'type': 'yg==' },
            { 'number': '647', 'name': 'Speed Reg Ki', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '653', 'name': 'Spd Loop Damping', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '654', 'name': 'Spd Reg Int Out', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '655', 'name': 'Spd Reg Pos Lmt', 'defaultValue': '300', 'record': 'true', 'type': 'yg==' },
            { 'number': '656', 'name': 'Spd Reg Neg Lmt', 'defaultValue': '-300', 'record': 'true', 'type': 'yg==' },
            { 'number': '660', 'name': 'SReg Output', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '663', 'name': 'VHzSV Spd Reg Kp', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '664', 'name': 'VHzSV Spd Reg Ki', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '665', 'name': 'Speed Comp Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '666', 'name': 'Speed Comp Gain', 'defaultValue': '-2.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '667', 'name': 'Speed Comp Out', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '670', 'name': 'Pos Torque Limit', 'defaultValue': '200', 'record': 'true', 'type': 'yg==' },
            { 'number': '671', 'name': 'Neg Torque Limit', 'defaultValue': '-200', 'record': 'true', 'type': 'yg==' },
            { 'number': '675', 'name': 'Trq Ref A Sel', 'defaultValue': '676', 'record': 'true', 'type': 'yA==' },
            { 'number': '676', 'name': 'Trq Ref A Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '677', 'name': 'Trq Ref A AnlgHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '678', 'name': 'Trq Ref A AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '679', 'name': 'Trq Ref A Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '680', 'name': 'Trq Ref B Sel', 'defaultValue': '681', 'record': 'true', 'type': 'yA==' },
            { 'number': '681', 'name': 'Trq Ref B Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '682', 'name': 'Trq Ref B AnlgHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '683', 'name': 'Trq Ref B AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '684', 'name': 'Trq Ref B Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '685', 'name': 'Selected Trq Ref', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '686', 'name': 'Torque Step', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '689', 'name': 'Filtered Trq Ref', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '690', 'name': 'Limited Trq Ref', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '720', 'name': 'PTP PsnRefStatus', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '721', 'name': 'Position Control', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '722', 'name': 'Psn Selected Ref', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '723', 'name': 'Psn Command', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '724', 'name': 'Psn Reg Status', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '725', 'name': 'Zero Position', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '726', 'name': 'In Pos Psn Band', 'defaultValue': '200', 'record': 'true', 'type': 'yA==' },
            { 'number': '727', 'name': 'In Pos Psn Dwell', 'defaultValue': '0.004', 'record': 'true', 'type': 'yg==' },
            { 'number': '730', 'name': 'Homing Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '731', 'name': 'Homing Control', 'defaultValue': '0000000000100000', 'record': 'true', 'type': '0g==' },
            { 'number': '732', 'name': 'DI Find Home', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '733', 'name': 'DI Redefine Psn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '734', 'name': 'DI OL Home Limit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '735', 'name': 'Find Home Speed', 'defaultValue': '6', 'record': 'true', 'type': 'yg==' },
            { 'number': '736', 'name': 'Find Home Ramp', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '737', 'name': 'Actual Home Psn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '738', 'name': 'User Home Psn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '739', 'name': 'Home Trq Thresh', 'defaultValue': '15', 'record': 'true', 'type': 'yg==' },
            { 'number': '740', 'name': 'Home Trq Time', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '741', 'name': 'Home Trq Level', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '742', 'name': 'Home Trq Offset', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '743', 'name': 'Home Return Spd', 'defaultValue': '0.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '744', 'name': 'Home Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '765', 'name': 'Psn Ref Select', 'defaultValue': '766', 'record': 'true', 'type': 'yA==' },
            { 'number': '766', 'name': 'Psn Direct Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '767', 'name': 'Psn Direct Ref', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '770', 'name': 'PTP Control', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '771', 'name': 'PTP Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '772', 'name': 'DI Indx Step', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '773', 'name': 'DI Indx StepRev', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '774', 'name': 'DI Indx StepPrst', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '775', 'name': 'PTP Ref Sel', 'defaultValue': '780', 'record': 'true', 'type': 'yA==' },
            { 'number': '776', 'name': 'PTP Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '777', 'name': 'PTP Feedback', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '778', 'name': 'PTP Ref Scale', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '779', 'name': 'PTP Index Preset', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '780', 'name': 'PTP Setpoint', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '781', 'name': 'PTP Accel Time', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '782', 'name': 'PTP Decel Time', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '783', 'name': 'PTP Speed FwdRef', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '784', 'name': 'PTP Command', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '785', 'name': 'PTP Fwd Vel Lmt', 'defaultValue': '30', 'record': 'true', 'type': 'yg==' },
            { 'number': '786', 'name': 'PTP Rev Vel Lmt', 'defaultValue': '-30', 'record': 'true', 'type': 'yg==' },
            { 'number': '787', 'name': 'PTP S Curve', 'defaultValue': '0.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '788', 'name': 'PTP Vel Override', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '789', 'name': 'PTP EGR Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '790', 'name': 'PTP EGR Div', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '815', 'name': 'Psn Ref EGR Out', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '816', 'name': 'Psn EGR Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '817', 'name': 'Psn EGR Div', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '820', 'name': 'Psn Offset 1 Sel', 'defaultValue': '821', 'record': 'true', 'type': 'yA==' },
            { 'number': '821', 'name': 'Psn Offset 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '822', 'name': 'Psn Offset 2 Sel', 'defaultValue': '823', 'record': 'true', 'type': 'yA==' },
            { 'number': '823', 'name': 'Psn Offset 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '824', 'name': 'Psn Offset Vel', 'defaultValue': '0.3', 'record': 'true', 'type': 'yg==' },
            { 'number': '835', 'name': 'Psn Error', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '836', 'name': 'Psn Actual', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '838', 'name': 'Psn Reg Ki', 'defaultValue': '4', 'record': 'true', 'type': 'yg==' },
            { 'number': '839', 'name': 'Psn Reg Kp', 'defaultValue': '4', 'record': 'true', 'type': 'yg==' },
            { 'number': '840', 'name': 'PReg Pos Int Lmt', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '841', 'name': 'PReg Neg Int Lmt', 'defaultValue': '-100', 'record': 'true', 'type': 'yg==' },
            { 'number': '842', 'name': 'PsnReg IntgrlOut', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '843', 'name': 'PsnReg Spd Out', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '844', 'name': 'PReg Pos Spd Lmt', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '845', 'name': 'PReg Neg Spd Lmt', 'defaultValue': '-10', 'record': 'true', 'type': 'yg==' },
            { 'number': '846', 'name': 'Psn Reg Droop', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '847', 'name': 'Psn Fdbk', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '848', 'name': 'Psn Gear Ratio', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '871', 'name': 'Port 1 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '872', 'name': 'Port 2 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '873', 'name': 'Port 3 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '874', 'name': 'Port 4 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '875', 'name': 'Port 5 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '876', 'name': 'Port 6 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '878', 'name': 'Port14 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '879', 'name': 'Drive Logic Rslt', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '880', 'name': 'DPI Ref Rslt', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '881', 'name': 'DPI Ramp Rslt', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '882', 'name': 'DPI Logic Rslt', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '883', 'name': 'Drive Ref Rslt', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '884', 'name': 'Drive Ramp Rslt', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '885', 'name': 'Port Mask Act', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '886', 'name': 'Logic Mask Act', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '887', 'name': 'Write Mask Act', 'defaultValue': '0000000001111110', 'record': 'false', 'type': '0g==' },
            { 'number': '888', 'name': 'Write Mask Cfg', 'defaultValue': '0100001001111110', 'record': 'true', 'type': '0g==' },
            { 'number': '895', 'name': 'Data In A1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '896', 'name': 'Data In A2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '897', 'name': 'Data In B1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '898', 'name': 'Data In B2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '899', 'name': 'Data In C1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '900', 'name': 'Data In C2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '901', 'name': 'Data In D1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '902', 'name': 'Data In D2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '905', 'name': 'Data Out A1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '906', 'name': 'Data Out A2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '907', 'name': 'Data Out B1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '908', 'name': 'Data Out B2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '909', 'name': 'Data Out C1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '910', 'name': 'Data Out C2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '911', 'name': 'Data Out D1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '912', 'name': 'Data Out D2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '919', 'name': 'Stop Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '920', 'name': 'Start Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '921', 'name': 'Jog Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '922', 'name': 'Dir Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '923', 'name': 'Clear Flt Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '924', 'name': 'Manual Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '925', 'name': 'Ref Select Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '930', 'name': 'Speed Ref Source', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '931', 'name': 'Last StartSource', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '932', 'name': 'Last Stop Source', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '933', 'name': 'Start Inhibits', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '934', 'name': 'Last StrtInhibit', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '935', 'name': 'Drive Status 1', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '936', 'name': 'Drive Status 2', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '937', 'name': 'Condition Sts 1', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '940', 'name': 'Drive OL Count', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '941', 'name': 'IGBT Temp Pct', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '942', 'name': 'IGBT Temp C', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '943', 'name': 'Drive Temp Pct', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '944', 'name': 'Drive Temp C', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '945', 'name': 'At Limit Status', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '946', 'name': 'Safety Port Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '950', 'name': 'Minor Flt Cfg', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '951', 'name': 'Last Fault Code', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '952', 'name': 'Fault Status A', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '953', 'name': 'Fault Status B', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '954', 'name': 'Status1 at Fault', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '955', 'name': 'Status2 at Fault', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '956', 'name': 'Fault Frequency', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '957', 'name': 'Fault Amps', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '958', 'name': 'Fault Bus Volts', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '959', 'name': 'Alarm Status A', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '960', 'name': 'Alarm Status B', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '961', 'name': 'Type 2 Alarms', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '962', 'name': 'AlarmA at Fault', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '963', 'name': 'AlarmB at Fault', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '964', 'name': 'MCB FPGA Actn', 'defaultValue': '6', 'record': 'true', 'type': 'yA==' },
            { 'number': '1065', 'name': 'PID Cfg', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '1066', 'name': 'PID Control', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '1067', 'name': 'PID Ref Sel', 'defaultValue': '1070', 'record': 'true', 'type': 'yA==' },
            { 'number': '1068', 'name': 'PID Ref AnlgHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1069', 'name': 'PID Ref AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1070', 'name': 'PID Setpoint', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1071', 'name': 'PID Ref Mult', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1072', 'name': 'PID Fdbk Sel', 'defaultValue': '1077', 'record': 'true', 'type': 'yA==' },
            { 'number': '1073', 'name': 'PID Fdbk AnlgHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1074', 'name': 'PID Fdbk AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1075', 'name': 'PID FBLoss SpSel', 'defaultValue': '546', 'record': 'true', 'type': 'yA==' },
            { 'number': '1076', 'name': 'PID FBLoss TqSel', 'defaultValue': '676', 'record': 'true', 'type': 'yA==' },
            { 'number': '1077', 'name': 'PID Fdbk', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1078', 'name': 'PID Fdbk Mult', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1079', 'name': 'PID Output Sel', 'defaultValue': '2', 'record': 'true', 'type': 'yA==' },
            { 'number': '1080', 'name': 'PID Output Mult', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1081', 'name': 'PID Upper Limit', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1082', 'name': 'PID Lower Limit', 'defaultValue': '-100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1083', 'name': 'PID Deadband', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1084', 'name': 'PID LP Filter BW', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1085', 'name': 'PID Preload', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1086', 'name': 'PID Prop Gain', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1087', 'name': 'PID Int Time', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1088', 'name': 'PID Deriv Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1089', 'name': 'PID Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '1090', 'name': 'PID Ref Meter', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1091', 'name': 'PID Fdbk Meter', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1092', 'name': 'PID Error Meter', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1093', 'name': 'PID Output Meter', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1120', 'name': 'Fiber Control', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '1121', 'name': 'Fiber Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '1122', 'name': 'Sync Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1123', 'name': 'Traverse Inc', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1124', 'name': 'Traverse Dec', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1125', 'name': 'Max Traverse', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1126', 'name': 'P Jump', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1129', 'name': 'DI Fiber SyncEna', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1130', 'name': 'DI Fiber TravDis', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1131', 'name': 'Adj Vltg Config', 'defaultValue': '0000000000000001', 'record': 'true', 'type': '0g==' },
            { 'number': '1133', 'name': 'Adj Vltg Select', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1134', 'name': 'Adj Vltg Ref Hi', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1135', 'name': 'Adj Vltg Ref Lo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1136', 'name': 'Adj Vltg TrimSel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1137', 'name': 'Adj Vltg Trim Hi', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1138', 'name': 'Adj Vltg Trim Lo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1139', 'name': 'Adj Vltg Command', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1140', 'name': 'Adj Vltg AccTime', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1141', 'name': 'Adj Vltg DecTime', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1142', 'name': 'Adj Vltg Preset1', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1143', 'name': 'Adj Vltg Preset2', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1144', 'name': 'Adj Vltg Preset3', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1145', 'name': 'Adj Vltg Preset4', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1146', 'name': 'Adj Vltg Preset5', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1147', 'name': 'Adj Vltg Preset6', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1148', 'name': 'Adj Vltg Preset7', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1149', 'name': 'Adj Vltg RefMult', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1150', 'name': 'Adj Vltg Scurve', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1151', 'name': 'Adj Vltg TrimPct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1152', 'name': 'Min Adj Voltage', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1153', 'name': 'Dead Time Comp', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1154', 'name': 'DC Offset Ctrl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1165', 'name': 'Rod Speed', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1166', 'name': 'Rod Torque', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1167', 'name': 'Rod Speed Cmd', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1168', 'name': 'TorqAlarm Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1169', 'name': 'TorqAlarm Config', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '1170', 'name': 'TorqAlarm Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1171', 'name': 'TorqAlarm Level', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1172', 'name': 'TorqAlm Timeout', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1173', 'name': 'TorqAlarm TOActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1174', 'name': 'Total Gear Ratio', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1175', 'name': 'Max Rod Speed', 'defaultValue': '300', 'record': 'true', 'type': 'yg==' },
            { 'number': '1176', 'name': 'Max Rod Torque', 'defaultValue': '500', 'record': 'true', 'type': 'yg==' },
            { 'number': '1177', 'name': 'Min Rod Speed', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1178', 'name': 'Motor Sheave', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1179', 'name': 'OilWell Pump Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1180', 'name': 'PCP Pump Sheave', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '1181', 'name': 'Gearbox Limit', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1182', 'name': 'Gearbox Rating', 'defaultValue': '640', 'record': 'true', 'type': 'yg==' },
            { 'number': '1183', 'name': 'Gearbox Ratio', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1184', 'name': 'Gearbox Sheave', 'defaultValue': '0.25', 'record': 'true', 'type': 'yg==' },
            { 'number': '1187', 'name': 'Pump Off Config', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1188', 'name': 'Pump Off Setup', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '1189', 'name': 'Pump Off Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1190', 'name': 'Pump Off Control', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1191', 'name': 'Pump Off Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '1192', 'name': 'Pump Cycle Store', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1193', 'name': 'Set Top ofStroke', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1194', 'name': 'Torque Setpoint', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1195', 'name': 'Pump Off Level', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '1196', 'name': 'Pump Off Speed', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '1197', 'name': 'Pump Off Time', 'defaultValue': '600', 'record': 'true', 'type': 'yg==' },
            { 'number': '1198', 'name': 'Pct Cycle Torque', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1199', 'name': 'Pct Lift Torque', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1200', 'name': 'Pct Drop Torque', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1201', 'name': 'Stroke Pos Count', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '1202', 'name': 'Stroke Per Min', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1203', 'name': 'Pump Off Count', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1204', 'name': 'PumpOff SleepCnt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1205', 'name': 'Day Stroke Count', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1206', 'name': 'DI PumpOff Disbl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1207', 'name': 'Pump OffSleepLvl', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1208', 'name': 'DI Pump Baseline', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1535', 'name': 'VB Config', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '1536', 'name': 'VB Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '1537', 'name': 'VB Voltage', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1538', 'name': 'VB Time', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1539', 'name': 'VB Minimum', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '1540', 'name': 'VB Maximum', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1541', 'name': 'VB Accel Rate', 'defaultValue': '0.75', 'record': 'true', 'type': 'yg==' },
            { 'number': '1542', 'name': 'VB Decel Rate', 'defaultValue': '6', 'record': 'true', 'type': 'yg==' },
            { 'number': '1543', 'name': 'VB Frequency', 'defaultValue': '0.8', 'record': 'true', 'type': 'yg==' },
            { 'number': '1544', 'name': 'VB Min Freq', 'defaultValue': '0.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '1545', 'name': 'VB Flux Thresh', 'defaultValue': '32.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '1546', 'name': 'VB Flux Lag Freq', 'defaultValue': '0.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '1547', 'name': 'VB Filt Flux Cur', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1548', 'name': 'VB Current Rate', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1549', 'name': 'VB Current Hyst', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1550', 'name': 'VB Cur Thresh', 'defaultValue': '-25', 'record': 'true', 'type': 'yg==' },
            { 'number': '1551', 'name': 'VB Rate Lag Freq', 'defaultValue': '2.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '1629', 'name': 'IPM Bus Prot', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1630', 'name': 'IPM_Lq_25_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1631', 'name': 'IPM_Lq_50_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1632', 'name': 'IPM_Lq_75_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1633', 'name': 'IPM_Lq_100_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1634', 'name': 'IPM_Lq_125_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1635', 'name': 'IPM_Ld_0_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1636', 'name': 'IPM_Ld_100_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1637', 'name': 'IPMVqFFwdCemf', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1638', 'name': 'IPMVqFFwdLdIdWe', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1639', 'name': 'IPMVdFFwdLqIqWe', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1640', 'name': 'IPM Max Cur', 'defaultValue': '200', 'record': 'true', 'type': 'yg==' },
            { 'number': '1641', 'name': 'IPM Max Spd', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1642', 'name': 'IPM TrqTrim Kp', 'defaultValue': '0.1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1643', 'name': 'IPM TrqTrim Ki', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1644', 'name': 'IPM TrqTrim HLim', 'defaultValue': '0.2', 'record': 'true', 'type': 'yg==' },
            { 'number': '1645', 'name': 'IPM TrqTrim LLim', 'defaultValue': '-0.2', 'record': 'true', 'type': 'yg==' },
            { 'number': '1660', 'name': 'IPM Stc OfsTst K', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1680', 'name': 'DI EmergencyOVRD', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1681', 'name': 'Emerg OVRD Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1682', 'name': 'Purge Frequency', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '1683', 'name': 'Emerg Prot OVRD', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '1684', 'name': 'EmergMode Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' }
        ]";
    }
}
