namespace powerFlexBackup.cipdevice.PortCards
{
    /// <summary>
    /// PowerFlex 755 Main Drive Controller
    ///
    /// PowerFlex 750 Series main drive at Port 0.
    /// ProductCode 2192 identifies the PowerFlex 755.
    ///
    /// 180 parameters (152 writable, 28 read-only).
    /// Types: 0g== (0xD2 DWORD), 0w== (0xD3 LWORD), yA== (0xC8 DINT), yg== (0xCA REAL)
    /// </summary>
    public class PF750_PortCard_PowerFlex755 : PowerFlex750PortCard
    {
        public override ushort[] ProductCodes => [2192];
        public override string ProductName => "PowerFlex 755";
        public override int ClassID => 0x9F;

        protected override string parameterListJSON => @"[
            { 'number': '1', 'name': 'Output Frequency', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '2', 'name': 'Commanded SpdRef', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '3', 'name': 'Mtr Vel Fdbk', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '4', 'name': 'Commanded Trq', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '5', 'name': 'Torque Cur Fdbk', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '6', 'name': 'Flux Cur Fdbk', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '7', 'name': 'Output Current', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '8', 'name': 'Output Voltage', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '9', 'name': 'Output Power', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '11', 'name': 'DC Bus Volts', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '20', 'name': 'Rated Volts', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '21', 'name': 'Rated Amps', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '22', 'name': 'Rated kW', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '25', 'name': 'Motor NP Volts', 'defaultValue': '460', 'record': 'true', 'type': 'yg==' },
            { 'number': '26', 'name': 'Motor NP Amps', 'defaultValue': '47.8', 'record': 'true', 'type': 'yg==' },
            { 'number': '27', 'name': 'Motor NP Hertz', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '28', 'name': 'Motor NP RPM', 'defaultValue': '1775', 'record': 'true', 'type': 'yg==' },
            { 'number': '29', 'name': 'Mtr NP Pwr Units', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '30', 'name': 'Motor NP Power', 'defaultValue': '40', 'record': 'true', 'type': 'yg==' },
            { 'number': '31', 'name': 'Motor Poles', 'defaultValue': '4', 'record': 'true', 'type': 'yA==' },
            { 'number': '35', 'name': 'Motor Ctrl Mode', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '36', 'name': 'Maximum Voltage', 'defaultValue': '460', 'record': 'true', 'type': 'yg==' },
            { 'number': '37', 'name': 'Maximum Freq', 'defaultValue': '130', 'record': 'true', 'type': 'yg==' },
            { 'number': '38', 'name': 'PWM Frequency', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '65', 'name': 'VHz Curve', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '70', 'name': 'Autotune', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '71', 'name': 'Autotune Torque', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '150', 'name': 'Digital In Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '155', 'name': 'DI Enable', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '156', 'name': 'DI Clear Fault', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '157', 'name': 'DI Aux Fault', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '158', 'name': 'DI Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '159', 'name': 'DI Cur Lmt Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '160', 'name': 'DI Coast Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '161', 'name': 'DI Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '162', 'name': 'DI Fwd Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '163', 'name': 'DI Run', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '164', 'name': 'DI Run Forward', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '165', 'name': 'DI Run Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '166', 'name': 'DI Jog 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '167', 'name': 'DI Jog 1 Forward', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '168', 'name': 'DI Jog 1 Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '169', 'name': 'DI Jog 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '170', 'name': 'DI Jog 2 Forward', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '171', 'name': 'DI Jog 2 Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '172', 'name': 'DI Manual Ctrl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '173', 'name': 'DI Speed Sel 0', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '174', 'name': 'DI Speed Sel 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '175', 'name': 'DI Speed Sel 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '176', 'name': 'DI HOA Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '179', 'name': 'DI Accel 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '180', 'name': 'DI Decel 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '220', 'name': 'Digital In Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '300', 'name': 'Speed Units', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '301', 'name': 'Access Level', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '302', 'name': 'Language', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '305', 'name': 'Voltage Class', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '306', 'name': 'Duty Rating', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '308', 'name': 'Direction Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '309', 'name': 'SpdTrqPsn Mode A', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '324', 'name': 'Logic Mask', 'defaultValue': '0110001111111111', 'record': 'true', 'type': '0g==' },
            { 'number': '325', 'name': 'Auto Mask', 'defaultValue': '0110000001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '326', 'name': 'Manual Cmd Mask', 'defaultValue': '0110000001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '327', 'name': 'Manual Ref Mask', 'defaultValue': '0000000000001111', 'record': 'true', 'type': '0g==' },
            { 'number': '328', 'name': 'Alt Man Ref Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '329', 'name': 'Alt Man Ref AnHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '330', 'name': 'Alt Man Ref AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '331', 'name': 'Manual Preload', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '370', 'name': 'Stop Mode A', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '371', 'name': 'Stop Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '372', 'name': 'Bus Reg Mode A', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '373', 'name': 'Bus Reg Mode B', 'defaultValue': '4', 'record': 'true', 'type': 'yA==' },
            { 'number': '382', 'name': 'DB Resistor Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '383', 'name': 'DB Ext Ohms', 'defaultValue': '15.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '384', 'name': 'DB Ext Watts', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '385', 'name': 'DB ExtPulseWatts', 'defaultValue': '2000', 'record': 'true', 'type': 'yg==' },
            { 'number': '392', 'name': 'Stop Dwell Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '409', 'name': 'Dec Inhibit Actn', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '410', 'name': 'Motor OL Actn', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '411', 'name': 'Mtr OL at Pwr Up', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '412', 'name': 'Mtr OL Alarm Lvl', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '413', 'name': 'Mtr OL Factor', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '414', 'name': 'Mtr OL Hertz', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '415', 'name': 'Mtr OL Reset Lvl', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '416', 'name': 'MtrOL Reset Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '421', 'name': 'Current Lmt Sel', 'defaultValue': '422', 'record': 'true', 'type': 'yA==' },
            { 'number': '422', 'name': 'Current Limit 1', 'defaultValue': '97.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '434', 'name': 'Shear Pin Cfg', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '435', 'name': 'Shear Pin 1 Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '436', 'name': 'Shear Pin1 Level', 'defaultValue': '52', 'record': 'true', 'type': 'yg==' },
            { 'number': '437', 'name': 'Shear Pin 1 Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '449', 'name': 'Power Loss Actn', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '450', 'name': 'Pwr Loss Mode A', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '520', 'name': 'Max Fwd Speed', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '521', 'name': 'Max Rev Speed', 'defaultValue': '-60', 'record': 'true', 'type': 'yg==' },
            { 'number': '522', 'name': 'Min Fwd Speed', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '523', 'name': 'Min Rev Speed', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '535', 'name': 'Accel Time 1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '536', 'name': 'Accel Time 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '537', 'name': 'Decel Time 1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '538', 'name': 'Decel Time 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '539', 'name': 'Jog Acc Dec Time', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '545', 'name': 'Spd Ref A Sel', 'defaultValue': '871', 'record': 'true', 'type': 'yA==' },
            { 'number': '546', 'name': 'Spd Ref A Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '547', 'name': 'Spd Ref A AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '548', 'name': 'Spd Ref A AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '550', 'name': 'Spd Ref B Sel', 'defaultValue': '551', 'record': 'true', 'type': 'yA==' },
            { 'number': '551', 'name': 'Spd Ref B Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '552', 'name': 'Spd Ref B AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '553', 'name': 'Spd Ref B AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '556', 'name': 'Jog Speed 1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '557', 'name': 'Jog Speed 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '566', 'name': 'MOP Init Select', 'defaultValue': '567', 'record': 'true', 'type': 'yA==' },
            { 'number': '567', 'name': 'MOP Init Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '571', 'name': 'Preset Speed 1', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '572', 'name': 'Preset Speed 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '573', 'name': 'Preset Speed 3', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '574', 'name': 'Preset Speed 4', 'defaultValue': '30', 'record': 'true', 'type': 'yg==' },
            { 'number': '575', 'name': 'Preset Speed 5', 'defaultValue': '40', 'record': 'true', 'type': 'yg==' },
            { 'number': '576', 'name': 'Preset Speed 6', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '577', 'name': 'Preset Speed 7', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '675', 'name': 'Trq Ref A Sel', 'defaultValue': '676', 'record': 'true', 'type': 'yA==' },
            { 'number': '676', 'name': 'Trq Ref A Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '677', 'name': 'Trq Ref A AnlgHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '678', 'name': 'Trq Ref A AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '679', 'name': 'Trq Ref A Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '680', 'name': 'Trq Ref B Sel', 'defaultValue': '681', 'record': 'true', 'type': 'yA==' },
            { 'number': '681', 'name': 'Trq Ref B Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '682', 'name': 'Trq Ref B AnlgHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '683', 'name': 'Trq Ref B AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '684', 'name': 'Trq Ref B Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '685', 'name': 'Selected Trq Ref', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '871', 'name': 'Port 1 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '895', 'name': 'Data In A1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '896', 'name': 'Data In A2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '897', 'name': 'Data In B1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '898', 'name': 'Data In B2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '899', 'name': 'Data In C1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '900', 'name': 'Data In C2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '901', 'name': 'Data In D1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '902', 'name': 'Data In D2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '905', 'name': 'Data Out A1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '906', 'name': 'Data Out A2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '907', 'name': 'Data Out B1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '908', 'name': 'Data Out B2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '909', 'name': 'Data Out C1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '910', 'name': 'Data Out C2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '911', 'name': 'Data Out D1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '912', 'name': 'Data Out D2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '930', 'name': 'Speed Ref Source', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '931', 'name': 'Last StartSource', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '932', 'name': 'Last Stop Source', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '933', 'name': 'Start Inhibits', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '934', 'name': 'Last StrtInhibit', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '935', 'name': 'Drive Status 1', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '936', 'name': 'Drive Status 2', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '937', 'name': 'Condition Sts 1', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '950', 'name': 'Minor Flt Cfg', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '951', 'name': 'Last Fault Code', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '952', 'name': 'Fault Status A', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '953', 'name': 'Fault Status B', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '1629', 'name': 'IPM Bus Prot', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1630', 'name': 'IPM_Lq_25_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1631', 'name': 'IPM_Lq_50_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1632', 'name': 'IPM_Lq_75_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1633', 'name': 'IPM_Lq_100_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1634', 'name': 'IPM_Lq_125_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1635', 'name': 'IPM_Ld_0_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1636', 'name': 'IPM_Ld_100_pct', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1637', 'name': 'IPMVqFFwdCemf', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1638', 'name': 'IPMVqFFwdLdIdWe', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1639', 'name': 'IPMVdFFwdLqIqWe', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1640', 'name': 'IPM Max Cur', 'defaultValue': '200', 'record': 'true', 'type': 'yg==' },
            { 'number': '1641', 'name': 'IPM Max Spd', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1642', 'name': 'IPM TrqTrim Kp', 'defaultValue': '0.1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1643', 'name': 'IPM TrqTrim Ki', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1644', 'name': 'IPM TrqTrim HLim', 'defaultValue': '0.2', 'record': 'true', 'type': 'yg==' },
            { 'number': '1645', 'name': 'IPM TrqTrim LLim', 'defaultValue': '-0.2', 'record': 'true', 'type': 'yg==' },
            { 'number': '1660', 'name': 'IPM Stc OfsTst K', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1684', 'name': 'EmergMode Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' }
        ]";
    }
}
