namespace powerFlexBackup.cipdevice.PortCards
{
    /// <summary>
    /// Dual-Port EtherNet/IP Communication Adapter
    ///
    /// PowerFlex 755 Series EtherNet/IP port with full network configuration.
    /// HOST class (0x9F): Datalinks and fault configuration (predefined, 54 params).
    /// DEVICE class (0x93): Full parameter set including DL config, IP config, subnet,
    /// gateway, BOOTP, web features, fault config, peer-to-peer config (predefined, 91 params).
    ///
    /// This is distinct from the embedded EtherNet/IP adapter (ProductCode 57760)
    /// which only has Datalinks, network I/O, and fault configuration.
    /// </summary>
    public class PF750_PortCard_EthernetIP_DualPort : PowerFlex750PortCard
    {
        public override ushort[] ProductCodes => [32928];
        public override string ProductName => "EtherNet/IP";
        public override int HostClassID => 0x9F;
        public override int? DeviceClassID => 0x93;
        public override bool UseScatteredRead => true;

        protected override string hostParameterListJSON => @"[
            { 'number': '1', 'name': 'DL From Net 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '2', 'name': 'DL From Net 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '3', 'name': 'DL From Net 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '4', 'name': 'DL From Net 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '5', 'name': 'DL From Net 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '6', 'name': 'DL From Net 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '7', 'name': 'DL From Net 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '8', 'name': 'DL From Net 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '9', 'name': 'DL From Net 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '10', 'name': 'DL From Net 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '11', 'name': 'DL From Net 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '12', 'name': 'DL From Net 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '13', 'name': 'DL From Net 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '14', 'name': 'DL From Net 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '15', 'name': 'DL From Net 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '16', 'name': 'DL From Net 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '17', 'name': 'DL To Net 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '18', 'name': 'DL To Net 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '19', 'name': 'DL To Net 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '20', 'name': 'DL To Net 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '21', 'name': 'DL To Net 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '22', 'name': 'DL To Net 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '23', 'name': 'DL To Net 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '24', 'name': 'DL To Net 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '25', 'name': 'DL To Net 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '26', 'name': 'DL To Net 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '27', 'name': 'DL To Net 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '28', 'name': 'DL To Net 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '29', 'name': 'DL To Net 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '30', 'name': 'DL To Net 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '31', 'name': 'DL To Net 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '32', 'name': 'DL To Net 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '33', 'name': 'Comm Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '34', 'name': 'Idle Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '35', 'name': 'Peer Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '36', 'name': 'Msg Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '37', 'name': 'Flt Cfg Logic', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '38', 'name': 'Flt Cfg Ref', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '39', 'name': 'Flt Cfg DL 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '40', 'name': 'Flt Cfg DL 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '41', 'name': 'Flt Cfg DL 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '42', 'name': 'Flt Cfg DL 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '43', 'name': 'Flt Cfg DL 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '44', 'name': 'Flt Cfg DL 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '45', 'name': 'Flt Cfg DL 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '46', 'name': 'Flt Cfg DL 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '47', 'name': 'Flt Cfg DL 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '48', 'name': 'Flt Cfg DL 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '49', 'name': 'Flt Cfg DL 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '50', 'name': 'Flt Cfg DL 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '51', 'name': 'Flt Cfg DL 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '52', 'name': 'Flt Cfg DL 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '53', 'name': 'Flt Cfg DL 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '54', 'name': 'Flt Cfg DL 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' }
        ]";

        protected override string? deviceParameterListJSON => @"[
            { 'number': '1', 'name': 'DL From Net 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '2', 'name': 'DL From Net 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '3', 'name': 'DL From Net 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '4', 'name': 'DL From Net 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '5', 'name': 'DL From Net 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '6', 'name': 'DL From Net 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '7', 'name': 'DL From Net 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '8', 'name': 'DL From Net 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '9', 'name': 'DL From Net 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '10', 'name': 'DL From Net 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '11', 'name': 'DL From Net 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '12', 'name': 'DL From Net 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '13', 'name': 'DL From Net 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '14', 'name': 'DL From Net 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '15', 'name': 'DL From Net 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '16', 'name': 'DL From Net 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '17', 'name': 'DL To Net 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '18', 'name': 'DL To Net 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '19', 'name': 'DL To Net 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '20', 'name': 'DL To Net 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '21', 'name': 'DL To Net 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '22', 'name': 'DL To Net 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '23', 'name': 'DL To Net 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '24', 'name': 'DL To Net 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '25', 'name': 'DL To Net 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '26', 'name': 'DL To Net 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '27', 'name': 'DL To Net 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '28', 'name': 'DL To Net 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '29', 'name': 'DL To Net 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '30', 'name': 'DL To Net 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '31', 'name': 'DL To Net 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '32', 'name': 'DL To Net 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '33', 'name': 'Port Number', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '34', 'name': 'DLs From Net Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '35', 'name': 'DLs To Net Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '36', 'name': 'BOOTP', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '37', 'name': 'Net Addr Src', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '38', 'name': 'IP Addr Cfg 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '39', 'name': 'IP Addr Cfg 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '40', 'name': 'IP Addr Cfg 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '41', 'name': 'IP Addr Cfg 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '42', 'name': 'Subnet Cfg 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '43', 'name': 'Subnet Cfg 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '44', 'name': 'Subnet Cfg 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '45', 'name': 'Subnet Cfg 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '46', 'name': 'Gateway Cfg 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '47', 'name': 'Gateway Cfg 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '48', 'name': 'Gateway Cfg 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '49', 'name': 'Gateway Cfg 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '50', 'name': 'Net Rate Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '51', 'name': 'Net Rate Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '52', 'name': 'Web Enable', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '53', 'name': 'Web Features', 'defaultValue': '0', 'record': 'true', 'type': '0g==' },
            { 'number': '54', 'name': 'Comm Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '55', 'name': 'Idle Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '56', 'name': 'Peer Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '57', 'name': 'Msg Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '58', 'name': 'Flt Cfg Logic', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '59', 'name': 'Flt Cfg Ref', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '60', 'name': 'Flt Cfg DL 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '61', 'name': 'Flt Cfg DL 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '62', 'name': 'Flt Cfg DL 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '63', 'name': 'Flt Cfg DL 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '64', 'name': 'Flt Cfg DL 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '65', 'name': 'Flt Cfg DL 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '66', 'name': 'Flt Cfg DL 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '67', 'name': 'Flt Cfg DL 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '68', 'name': 'Flt Cfg DL 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '69', 'name': 'Flt Cfg DL 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '70', 'name': 'Flt Cfg DL 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '71', 'name': 'Flt Cfg DL 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '72', 'name': 'Flt Cfg DL 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '73', 'name': 'Flt Cfg DL 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '74', 'name': 'Flt Cfg DL 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '75', 'name': 'Flt Cfg DL 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '76', 'name': 'DLs Fr Peer Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '77', 'name': 'DLs Fr Peer Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '78', 'name': 'Logic Src Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '79', 'name': 'Ref Src Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '80', 'name': 'Fr Peer Timeout', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '81', 'name': 'Fr Peer Addr 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '82', 'name': 'Fr Peer Addr 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '83', 'name': 'Fr Peer Addr 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '84', 'name': 'Fr Peer Addr 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '85', 'name': 'Fr Peer Enable', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '86', 'name': 'Fr Peer Status', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '87', 'name': 'DLs To Peer Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '88', 'name': 'DLs To Peer Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '89', 'name': 'To Peer Period', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '90', 'name': 'To Peer Skip', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '91', 'name': 'To Peer Enable', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' }
        ]";
    }
}
