namespace powerFlexBackup.cipdevice.PortCards
{
    /// <summary>
    /// Port 10 - Induction VHz Port Card
    ///
    /// 497 parameters (426 writable, 71 read-only).
    /// Types: xg== (0xC6 INT), yA== (0xC8 DINT), yg== (0xCA REAL), 0g== (0xD2 DWORD), 0w== (0xD3 LWORD)
    /// </summary>
    public class PF750_PortCard_Port10InductionVHz : PowerFlex750PortCard
    {
        public override ushort[] ProductCodes => [161];
        public override string ProductName => "Induction VHz";
        public override int HostClassID => 0x9F;

        protected override string hostParameterListJSON => @"[
            { 'number': '1', 'name': 'Output Frequency', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '2', 'name': 'Output Voltage', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '3', 'name': 'Output Current', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '4', 'name': 'Output Power', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '5', 'name': 'Output Pwr Factr', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '8', 'name': 'Torque Cur Fb', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '9', 'name': 'Flux Cur Fb', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '11', 'name': 'Motor Voltage Fb', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '13', 'name': 'DC Bus Memory', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '20', 'name': 'Rated Volts', 'defaultValue': '480', 'record': 'false', 'type': 'yg==' },
            { 'number': '21', 'name': 'Rated Amps', 'defaultValue': '40', 'record': 'false', 'type': 'yg==' },
            { 'number': '22', 'name': 'Rated kW', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '30', 'name': 'PsnVelTrq Mode A', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '31', 'name': 'PsnVelTrq Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '32', 'name': 'PsnVelTrq Mode C', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '33', 'name': 'PsnVelTrq Mode D', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '34', 'name': 'PsnVelTrq Actv', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '50', 'name': 'Start At PowerUp', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '52', 'name': 'PowerUp Delay', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '70', 'name': 'FlyingStart Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '71', 'name': 'FS Kp CEMF', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '72', 'name': 'FS Ki CEMF', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '73', 'name': 'FS VReg Kp CEMF', 'defaultValue': '75', 'record': 'true', 'type': 'yg==' },
            { 'number': '74', 'name': 'FS VReg Ki CEMF', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '75', 'name': 'FS ExciteKp CEMF', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '76', 'name': 'FS ExciteKi CEMF', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '77', 'name': 'FS RecntDly CEMF', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '78', 'name': 'FS Brk Lvl CEMF', 'defaultValue': '28', 'record': 'true', 'type': 'yg==' },
            { 'number': '79', 'name': 'FS Brk Time CEMF', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '80', 'name': 'FSZSpdThreshCEMF', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '85', 'name': 'FS ZSpdThreshSwp', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '86', 'name': 'FS RecntDly Swp', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '87', 'name': 'FS Brk Lvl Swp', 'defaultValue': '28', 'record': 'true', 'type': 'yg==' },
            { 'number': '88', 'name': 'FS Brk Time Swp', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '89', 'name': 'FS FreqSwpTm Swp', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '90', 'name': 'FS VHz EndPt Swp', 'defaultValue': '1.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '91', 'name': 'FS VHz Fixed Swp', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '92', 'name': 'FS InitVltKp Swp', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '93', 'name': 'FS InitVltKi Swp', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '94', 'name': 'FS Recvr Ki Swp', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '95', 'name': 'FS VReg Kp Swp', 'defaultValue': '75', 'record': 'true', 'type': 'yg==' },
            { 'number': '96', 'name': 'FS VReg Ki Swp', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '97', 'name': 'FS SpdDetLvl Swp', 'defaultValue': '75', 'record': 'true', 'type': 'yg==' },
            { 'number': '98', 'name': 'FS SpdDtcTim Swp', 'defaultValue': '0.06', 'record': 'true', 'type': 'yg==' },
            { 'number': '110', 'name': 'Mtr Stop Mode A', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '111', 'name': 'Mtr Stop Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '116', 'name': 'Bus Reg Mode A', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '117', 'name': 'Bus Reg Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '118', 'name': 'Bus Reg Lvl Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '119', 'name': 'Bus Reg Level', 'defaultValue': '746.7048', 'record': 'true', 'type': 'yg==' },
            { 'number': '122', 'name': 'Bus Limit Kp', 'defaultValue': '1170', 'record': 'true', 'type': 'yg==' },
            { 'number': '123', 'name': 'Bus Limit Kd', 'defaultValue': '152', 'record': 'true', 'type': 'yg==' },
            { 'number': '124', 'name': 'Bus Limit ACR Kp', 'defaultValue': '524', 'record': 'true', 'type': 'yg==' },
            { 'number': '125', 'name': 'Bus Limit ACR Ki', 'defaultValue': '2045', 'record': 'true', 'type': 'yg==' },
            { 'number': '130', 'name': 'DB Resistor Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '131', 'name': 'DB Ext Ohms', 'defaultValue': '15.8', 'record': 'true', 'type': 'yg==' },
            { 'number': '132', 'name': 'DB Ext Watts', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '133', 'name': 'DB ExtPulseWatts', 'defaultValue': '2000', 'record': 'true', 'type': 'yg==' },
            { 'number': '138', 'name': 'Flux Braking En', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '139', 'name': 'Flux Braking Kp', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '140', 'name': 'Flux Braking Ki', 'defaultValue': '10000', 'record': 'true', 'type': 'yg==' },
            { 'number': '141', 'name': 'Flux Braking Lim', 'defaultValue': '125', 'record': 'true', 'type': 'yg==' },
            { 'number': '145', 'name': 'Stop Dwell Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '146', 'name': 'Zero Speed Limit', 'defaultValue': '0.059000004', 'record': 'true', 'type': 'yg==' },
            { 'number': '151', 'name': 'DC Brake Lvl Sel', 'defaultValue': '100152', 'record': 'true', 'type': 'yA==' },
            { 'number': '152', 'name': 'DC Brake Level', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '153', 'name': 'DC Brake Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '154', 'name': 'DCBrk Cur Reg BW', 'defaultValue': '127', 'record': 'true', 'type': 'yg==' },
            { 'number': '157', 'name': 'DC Brk Vq Fltr', 'defaultValue': '250', 'record': 'true', 'type': 'yg==' },
            { 'number': '163', 'name': 'Fast Braking Kp', 'defaultValue': '0.0015', 'record': 'true', 'type': 'yg==' },
            { 'number': '164', 'name': 'Fast Braking Ki', 'defaultValue': '0.1', 'record': 'true', 'type': 'yg==' },
            { 'number': '165', 'name': 'Fast Brake Power', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '166', 'name': 'Fast Brake Freq', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '170', 'name': 'Dec Inhibit Actn', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '200', 'name': 'Mtr OL Action', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '201', 'name': 'Mtr OL at Pwr Up', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '202', 'name': 'Mtr OL Alm Level', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '203', 'name': 'Mtr OL Factor', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '204', 'name': 'Mtr OL Hertz', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '205', 'name': 'Mtr OL Rst Level', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '206', 'name': 'Mtr OL Rst Time', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '207', 'name': 'Mtr OL Counts', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '208', 'name': 'Mtr OL Trip Time', 'defaultValue': '99999', 'record': 'false', 'type': 'yA==' },
            { 'number': '209', 'name': 'Mtr Protn Class', 'defaultValue': '11', 'record': 'true', 'type': 'yA==' },
            { 'number': '210', 'name': 'Mtr HotStrtCoeff', 'defaultValue': '0.33', 'record': 'true', 'type': 'yg==' },
            { 'number': '211', 'name': 'Mtr Cooling Time', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '220', 'name': 'Drive OL Mode', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '221', 'name': 'Current Lim Sel', 'defaultValue': '100222', 'record': 'true', 'type': 'yA==' },
            { 'number': '222', 'name': 'Current Limit 1', 'defaultValue': '79.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '223', 'name': 'Current Limit 2', 'defaultValue': '79.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '224', 'name': 'Active Cur Lim', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '232', 'name': 'Current Limit Kp', 'defaultValue': '290', 'record': 'true', 'type': 'yg==' },
            { 'number': '233', 'name': 'Current Limit Ki', 'defaultValue': '680', 'record': 'true', 'type': 'yg==' },
            { 'number': '234', 'name': 'Current Limit Kd', 'defaultValue': '760', 'record': 'true', 'type': 'yg==' },
            { 'number': '236', 'name': 'Id Lo FreqCur Kp', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '237', 'name': 'Iq Lo FreqCur Kp', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '239', 'name': 'Jerk Gain', 'defaultValue': '5200', 'record': 'true', 'type': 'yg==' },
            { 'number': '241', 'name': 'Shear Pin Config', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '242', 'name': 'Shear Pin 1 Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '243', 'name': 'Shear Pin1 Level', 'defaultValue': '40', 'record': 'true', 'type': 'yg==' },
            { 'number': '244', 'name': 'Shear Pin 1 Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '245', 'name': 'Shear Pin 2 Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '246', 'name': 'Shear Pin2 Level', 'defaultValue': '40', 'record': 'true', 'type': 'yg==' },
            { 'number': '247', 'name': 'Shear Pin 2 Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '250', 'name': 'Load Loss Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '251', 'name': 'Load Loss Level', 'defaultValue': '200', 'record': 'true', 'type': 'yg==' },
            { 'number': '252', 'name': 'Load Loss Time', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '253', 'name': 'Load Loss Speed', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '256', 'name': 'OutPhaseLossActn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '257', 'name': 'OutPhaseLoss Lvl', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '270', 'name': 'Power Loss Actn', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '271', 'name': 'Pwr Loss Mode A', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '272', 'name': 'Pwr Loss A Level', 'defaultValue': '187.82399', 'record': 'true', 'type': 'yg==' },
            { 'number': '273', 'name': 'Pwr Loss A Time', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '275', 'name': 'Pwr Loss Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '276', 'name': 'Pwr Loss B Level', 'defaultValue': '187.82399', 'record': 'true', 'type': 'yg==' },
            { 'number': '277', 'name': 'Pwr Loss B Time', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '279', 'name': 'PwrLoss RT BusKp', 'defaultValue': '585', 'record': 'true', 'type': 'yg==' },
            { 'number': '280', 'name': 'PwrLoss RT BusKd', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '281', 'name': 'PwrLoss RT ACRKp', 'defaultValue': '524', 'record': 'true', 'type': 'yg==' },
            { 'number': '282', 'name': 'PwrLoss RT ACRKi', 'defaultValue': '2045', 'record': 'true', 'type': 'yg==' },
            { 'number': '285', 'name': 'UnderVltg Action', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '286', 'name': 'UnderVltg Level', 'defaultValue': '300', 'record': 'true', 'type': 'yg==' },
            { 'number': '289', 'name': 'InPhase LossActn', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '290', 'name': 'InPhase Loss Lvl', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '292', 'name': 'DC Bus Mem Reset', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '350', 'name': 'VRef Source', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '351', 'name': 'M Start Inhibits', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '352', 'name': 'MLastStrtInhibit', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '354', 'name': 'Motor Side Sts 1', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '355', 'name': 'Motor Side Sts 2', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '357', 'name': 'Drive OL Count', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '359', 'name': 'IGBT Temp Pct', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '360', 'name': 'IGBT Temp', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '362', 'name': 'Heatsnk Temp Pct', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '363', 'name': 'Heatsnk Temp', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '365', 'name': 'At Limit Status', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '380', 'name': 'Testpoint Sel 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '381', 'name': 'Testpoint REAL 1', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '382', 'name': 'Testpoint DINT 1', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '383', 'name': 'Testpoint Sel 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '384', 'name': 'Testpoint REAL 2', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '385', 'name': 'Testpoint DINT 2', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '386', 'name': 'Testpoint Sel 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '387', 'name': 'Testpoint REAL 3', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '388', 'name': 'Testpoint DINT 3', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '389', 'name': 'Testpoint Sel 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '390', 'name': 'Testpoint REAL 4', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '391', 'name': 'Testpoint DINT 4', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '400', 'name': 'Motor NP Volts', 'defaultValue': '460', 'record': 'true', 'type': 'yg==' },
            { 'number': '401', 'name': 'Motor NP Amps', 'defaultValue': '36.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '402', 'name': 'Motor NP Hertz', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '403', 'name': 'Motor NP RPM', 'defaultValue': '1770', 'record': 'true', 'type': 'yg==' },
            { 'number': '404', 'name': 'Mtr NP Sync Spd', 'defaultValue': '1800', 'record': 'false', 'type': 'yg==' },
            { 'number': '405', 'name': 'Mtr NP Pwr Units', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '406', 'name': 'Motor NP Power', 'defaultValue': '30', 'record': 'true', 'type': 'yg==' },
            { 'number': '407', 'name': 'Motor Poles', 'defaultValue': '4', 'record': 'true', 'type': 'yA==' },
            { 'number': '420', 'name': 'Mtr Cfg Options', 'defaultValue': '00000000000000001000110001100111', 'record': 'true', 'type': '0w==' },
            { 'number': '421', 'name': 'Maximum Voltage', 'defaultValue': '460', 'record': 'true', 'type': 'yg==' },
            { 'number': '422', 'name': 'Maximum Freq', 'defaultValue': '120', 'record': 'true', 'type': 'yg==' },
            { 'number': '425', 'name': 'PWM Frequency', 'defaultValue': '1', 'record': 'true', 'type': 'xg==' },
            { 'number': '426', 'name': 'PWM Freq Act', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '428', 'name': 'Bus Utilization', 'defaultValue': '95', 'record': 'true', 'type': 'yg==' },
            { 'number': '429', 'name': 'PWM Trans Freq', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '431', 'name': 'FluxUpTm C/U Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '432', 'name': 'c FluxUpTime', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '433', 'name': 'u FluxUpTime', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '435', 'name': 'Flux Down Kp', 'defaultValue': '150', 'record': 'true', 'type': 'yg==' },
            { 'number': '436', 'name': 'Flux Down Ki', 'defaultValue': '0.2', 'record': 'true', 'type': 'yg==' },
            { 'number': '439', 'name': 'Stability Filter', 'defaultValue': '5162.22', 'record': 'true', 'type': 'yg==' },
            { 'number': '440', 'name': 'Stab Volt Gain', 'defaultValue': '5162.22', 'record': 'true', 'type': 'yg==' },
            { 'number': '441', 'name': 'Stab Angle Gain', 'defaultValue': '790.43', 'record': 'true', 'type': 'yg==' },
            { 'number': '445', 'name': 'VCL CReg BW', 'defaultValue': '191', 'record': 'true', 'type': 'yg==' },
            { 'number': '450', 'name': 'VCL CReg Damping', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '451', 'name': 'DeadTimeCompAmps', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '452', 'name': 'Dead Time Comp', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '453', 'name': 'DC Offset Ctrl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '460', 'name': 'Condition Sts A', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '461', 'name': 'Fault Status A', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '462', 'name': 'Fault Status B', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '465', 'name': 'Alarm Status A', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '466', 'name': 'Alarm Status B', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '467', 'name': 'Type 2 Alarms', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '480', 'name': 'Start Acc Boost', 'defaultValue': '6.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '481', 'name': 'Run Boost', 'defaultValue': '6.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '483', 'name': 'Break Voltage', 'defaultValue': '115', 'record': 'true', 'type': 'yg==' },
            { 'number': '484', 'name': 'Break Frequency', 'defaultValue': '15', 'record': 'true', 'type': 'yg==' },
            { 'number': '486', 'name': 'VHz Curve', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '489', 'name': 'c Slip RPM atFLA', 'defaultValue': '20', 'record': 'false', 'type': 'yg==' },
            { 'number': '490', 'name': 'u Slip RPM atFLA', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '491', 'name': 'Slip Comp LPF BW', 'defaultValue': '1.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '510', 'name': 'MtrParam C/U Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '511', 'name': 'c IM Stator Res', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '512', 'name': 'u IM Stator Res', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '514', 'name': 'c IM Leakage L', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '515', 'name': 'u IM Leakage L', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '517', 'name': 'c Flux Cur Ref', 'defaultValue': '16.484999', 'record': 'false', 'type': 'yg==' },
            { 'number': '518', 'name': 'u Flux Cur Ref', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '820', 'name': 'VB Config', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '821', 'name': 'VB Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '822', 'name': 'VB Voltage', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '823', 'name': 'VB Time', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '824', 'name': 'VB Minimum', 'defaultValue': '2', 'record': 'true', 'type': 'yg==' },
            { 'number': '825', 'name': 'VB Maximum', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '826', 'name': 'VB Accel Rate', 'defaultValue': '0.75', 'record': 'true', 'type': 'yg==' },
            { 'number': '827', 'name': 'VB Decel Rate', 'defaultValue': '6', 'record': 'true', 'type': 'yg==' },
            { 'number': '828', 'name': 'VB Frequency', 'defaultValue': '0.8', 'record': 'true', 'type': 'yg==' },
            { 'number': '829', 'name': 'VB Freq Min', 'defaultValue': '0.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '830', 'name': 'VB Flux Thresh', 'defaultValue': '38.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '831', 'name': 'VB Flux Lag Freq', 'defaultValue': '0.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '832', 'name': 'VB Flux Cur Filt', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '833', 'name': 'VB Current Rate', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '834', 'name': 'VB Current Hyst', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '835', 'name': 'VB Cur Thresh', 'defaultValue': '-25', 'record': 'true', 'type': 'yg==' },
            { 'number': '836', 'name': 'VB Rate Lag Freq', 'defaultValue': '2.6', 'record': 'true', 'type': 'yg==' },
            { 'number': '910', 'name': 'Autotune', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '912', 'name': 'Autotune Vel Lim', 'defaultValue': '75', 'record': 'true', 'type': 'yg==' },
            { 'number': '913', 'name': 'Autotune Trq Lim', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '930', 'name': 'Direction Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '942', 'name': 'Ref NF1 Freq', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '943', 'name': 'Ref NF1 Width', 'defaultValue': '0.707', 'record': 'true', 'type': 'yg==' },
            { 'number': '944', 'name': 'Ref NF1 Depth', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '945', 'name': 'Ref NF1 Gain', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '948', 'name': 'Ref NF2 Freq', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '949', 'name': 'Ref NF2 Width', 'defaultValue': '0.707', 'record': 'true', 'type': 'yg==' },
            { 'number': '950', 'name': 'Ref NF2 Depth', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '951', 'name': 'Ref NF2 Gain', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '954', 'name': 'Ref NF1 Freq Act', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '956', 'name': 'RefNF1 Depth Act', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '957', 'name': 'Ref NF1 Gain Act', 'defaultValue': '1', 'record': 'false', 'type': 'yg==' },
            { 'number': '966', 'name': 'Crane Length 1', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1042', 'name': 'Vel Fb Active', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1044', 'name': 'Motor Vel Fb', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1200', 'name': 'Profile Status', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '1201', 'name': 'Units Traveled', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1202', 'name': 'Profile Command', 'defaultValue': '00000000000000000001100000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '1203', 'name': 'Counts Per Unit', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1204', 'name': 'ProfVel Override', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1205', 'name': 'Step 1 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1206', 'name': 'Step 1 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1207', 'name': 'Step 1 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1208', 'name': 'Step 1 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1209', 'name': 'Step 1 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1210', 'name': 'Step 1 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1211', 'name': 'Step 1 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1212', 'name': 'Step 1 Next', 'defaultValue': '2', 'record': 'true', 'type': 'yA==' },
            { 'number': '1213', 'name': 'Step 1 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1214', 'name': 'S1 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1215', 'name': 'S1 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1216', 'name': 'Step 2 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1217', 'name': 'Step 2 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1218', 'name': 'Step 2 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1219', 'name': 'Step 2 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1220', 'name': 'Step 2 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1221', 'name': 'Step 2 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1222', 'name': 'Step 2 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1223', 'name': 'Step 2 Next', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '1224', 'name': 'Step 2 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1225', 'name': 'S2 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1226', 'name': 'S2 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1227', 'name': 'Step 3 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1228', 'name': 'Step 3 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1229', 'name': 'Step 3 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1230', 'name': 'Step 3 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1231', 'name': 'Step 3 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1232', 'name': 'Step 3 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1233', 'name': 'Step 3 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1234', 'name': 'Step 3 Next', 'defaultValue': '4', 'record': 'true', 'type': 'yA==' },
            { 'number': '1235', 'name': 'Step 3 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1236', 'name': 'S3 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1237', 'name': 'S3 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1238', 'name': 'Step 4 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1239', 'name': 'Step 4 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1240', 'name': 'Step 4 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1241', 'name': 'Step 4 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1242', 'name': 'Step 4 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1243', 'name': 'Step 4 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1244', 'name': 'Step 4 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1245', 'name': 'Step 4 Next', 'defaultValue': '5', 'record': 'true', 'type': 'yA==' },
            { 'number': '1246', 'name': 'Step 4 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1247', 'name': 'S4 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1248', 'name': 'S4 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1249', 'name': 'Step 5 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1250', 'name': 'Step 5 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1251', 'name': 'Step 5 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1252', 'name': 'Step 5 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1253', 'name': 'Step 5 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1254', 'name': 'Step 5 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1255', 'name': 'Step 5 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1256', 'name': 'Step 5 Next', 'defaultValue': '6', 'record': 'true', 'type': 'yA==' },
            { 'number': '1257', 'name': 'Step 5 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1258', 'name': 'S5 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1259', 'name': 'S5 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1260', 'name': 'Step 6 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1261', 'name': 'Step 6 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1262', 'name': 'Step 6 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1263', 'name': 'Step 6 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1264', 'name': 'Step 6 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1265', 'name': 'Step 6 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1266', 'name': 'Step 6 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1267', 'name': 'Step 6 Next', 'defaultValue': '7', 'record': 'true', 'type': 'yA==' },
            { 'number': '1268', 'name': 'Step 6 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1269', 'name': 'S6 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1270', 'name': 'S6 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1271', 'name': 'Step 7 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1272', 'name': 'Step 7 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1273', 'name': 'Step 7 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1274', 'name': 'Step 7 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1275', 'name': 'Step 7 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1276', 'name': 'Step 7 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1277', 'name': 'Step 7 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1278', 'name': 'Step 7 Next', 'defaultValue': '8', 'record': 'true', 'type': 'yA==' },
            { 'number': '1279', 'name': 'Step 7 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1280', 'name': 'S7 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1281', 'name': 'S7 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1282', 'name': 'Step 8 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1283', 'name': 'Step 8 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1284', 'name': 'Step 8 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1285', 'name': 'Step 8 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1286', 'name': 'Step 8 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1287', 'name': 'Step 8 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1288', 'name': 'Step 8 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1289', 'name': 'Step 8 Next', 'defaultValue': '9', 'record': 'true', 'type': 'yA==' },
            { 'number': '1290', 'name': 'Step 8 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1291', 'name': 'S8 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1292', 'name': 'S8 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1293', 'name': 'Step 9 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1294', 'name': 'Step 9 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1295', 'name': 'Step 9 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1296', 'name': 'Step 9 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1297', 'name': 'Step 9 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1298', 'name': 'Step 9 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1299', 'name': 'Step 9 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1300', 'name': 'Step 9 Next', 'defaultValue': '10', 'record': 'true', 'type': 'yA==' },
            { 'number': '1301', 'name': 'Step 9 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1302', 'name': 'S9 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1303', 'name': 'S9 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1304', 'name': 'Step 10 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1305', 'name': 'Step 10 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1306', 'name': 'Step 10 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1307', 'name': 'Step 10 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1308', 'name': 'Step 10 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1309', 'name': 'Step 10 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1310', 'name': 'Step 10 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1311', 'name': 'Step 10 Next', 'defaultValue': '11', 'record': 'true', 'type': 'yA==' },
            { 'number': '1312', 'name': 'Step 10 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1313', 'name': 'S10 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1314', 'name': 'S10 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1315', 'name': 'Step 11 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1316', 'name': 'Step 11 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1317', 'name': 'Step 11 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1318', 'name': 'Step 11 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1319', 'name': 'Step 11 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1320', 'name': 'Step 11 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1321', 'name': 'Step 11 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1322', 'name': 'Step 11 Next', 'defaultValue': '12', 'record': 'true', 'type': 'yA==' },
            { 'number': '1323', 'name': 'Step 11 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1324', 'name': 'S11 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1325', 'name': 'S11 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1326', 'name': 'Step 12 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1327', 'name': 'Step 12 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1328', 'name': 'Step 12 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1329', 'name': 'Step 12 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1330', 'name': 'Step 12 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1331', 'name': 'Step 12 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1332', 'name': 'Step 12 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1333', 'name': 'Step 12 Next', 'defaultValue': '13', 'record': 'true', 'type': 'yA==' },
            { 'number': '1334', 'name': 'Step 12 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1335', 'name': 'S12 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1336', 'name': 'S12 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1337', 'name': 'Step 13 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1338', 'name': 'Step 13 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1339', 'name': 'Step 13 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1340', 'name': 'Step 13 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1341', 'name': 'Step 13 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1342', 'name': 'Step 13 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1343', 'name': 'Step 13 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1344', 'name': 'Step 13 Next', 'defaultValue': '14', 'record': 'true', 'type': 'yA==' },
            { 'number': '1345', 'name': 'Step 13 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1346', 'name': 'S13 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1347', 'name': 'S13 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1348', 'name': 'Step 14 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1349', 'name': 'Step 14 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1350', 'name': 'Step 14 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1351', 'name': 'Step 14 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1352', 'name': 'Step 14 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1353', 'name': 'Step 14 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1354', 'name': 'Step 14 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1355', 'name': 'Step 14 Next', 'defaultValue': '15', 'record': 'true', 'type': 'yA==' },
            { 'number': '1356', 'name': 'Step 14 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1357', 'name': 'S14 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1358', 'name': 'S14 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1359', 'name': 'Step 15 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1360', 'name': 'Step 15 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1361', 'name': 'Step 15 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1362', 'name': 'Step 15 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1363', 'name': 'Step 15 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1364', 'name': 'Step 15 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1365', 'name': 'Step 15 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1366', 'name': 'Step 15 Next', 'defaultValue': '16', 'record': 'true', 'type': 'yA==' },
            { 'number': '1367', 'name': 'Step 15 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1368', 'name': 'S15 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1369', 'name': 'S15 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1370', 'name': 'Step 16 Type', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1371', 'name': 'Step 16 Velocity', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1372', 'name': 'Step 16 Accel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1373', 'name': 'Step 16 Decel', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1374', 'name': 'Step 16 Value', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1375', 'name': 'Step 16 Dwell', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1376', 'name': 'Step 16 Batch', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1377', 'name': 'Step 16 Next', 'defaultValue': '16', 'record': 'true', 'type': 'yA==' },
            { 'number': '1378', 'name': 'Step 16 Action', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1379', 'name': 'S16 Blend P1 Sel', 'defaultValue': '101042', 'record': 'true', 'type': 'yA==' },
            { 'number': '1419', 'name': 'S16 Blend P2 Sel', 'defaultValue': '800', 'record': 'true', 'type': 'yA==' },
            { 'number': '1640', 'name': 'Home Ctrl Opts', 'defaultValue': '0000000000100000', 'record': 'true', 'type': '0g==' },
            { 'number': '1641', 'name': 'Home Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '1643', 'name': 'Find Home Speed', 'defaultValue': '5.9', 'record': 'true', 'type': 'yg==' },
            { 'number': '1644', 'name': 'Find Home Ramp', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1800', 'name': 'VRef A Sel', 'defaultValue': '214', 'record': 'true', 'type': 'yA==' },
            { 'number': '1801', 'name': 'VRef A Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1802', 'name': 'VRef A AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1803', 'name': 'VRef A AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1804', 'name': 'VRef A Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1807', 'name': 'VRef B Sel', 'defaultValue': '101808', 'record': 'true', 'type': 'yA==' },
            { 'number': '1808', 'name': 'VRef B Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1809', 'name': 'VRef B AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1810', 'name': 'VRef B AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1811', 'name': 'VRef B Mult', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '1814', 'name': 'Preset Speed 1', 'defaultValue': '5', 'record': 'true', 'type': 'yg==' },
            { 'number': '1815', 'name': 'Preset Speed 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1816', 'name': 'Preset Speed 3', 'defaultValue': '20', 'record': 'true', 'type': 'yg==' },
            { 'number': '1817', 'name': 'Preset Speed 4', 'defaultValue': '30', 'record': 'true', 'type': 'yg==' },
            { 'number': '1818', 'name': 'Preset Speed 5', 'defaultValue': '40', 'record': 'true', 'type': 'yg==' },
            { 'number': '1819', 'name': 'Preset Speed 6', 'defaultValue': '50', 'record': 'true', 'type': 'yg==' },
            { 'number': '1820', 'name': 'Preset Speed 7', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1823', 'name': 'MOP Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1824', 'name': 'MOP Ref Save', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '1825', 'name': 'MOP Rate', 'defaultValue': '1.0000005', 'record': 'true', 'type': 'yg==' },
            { 'number': '1826', 'name': 'MOP Limit High', 'defaultValue': '100.00004', 'record': 'true', 'type': 'yg==' },
            { 'number': '1827', 'name': 'MOP Limit Low', 'defaultValue': '-100.00004', 'record': 'true', 'type': 'yg==' },
            { 'number': '1828', 'name': 'MOP Init Select', 'defaultValue': '101829', 'record': 'true', 'type': 'yA==' },
            { 'number': '1829', 'name': 'MOP Init Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1832', 'name': 'Enc VRef Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1833', 'name': 'Enc VRef Taps', 'defaultValue': '0', 'record': 'true', 'type': 'xg==' },
            { 'number': '1834', 'name': 'Enc VRef', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1835', 'name': 'Alt Man Ref Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '1836', 'name': 'Alt Man Ref AnHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1837', 'name': 'Alt Man Ref AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1840', 'name': 'ManRef DI AnlgHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1841', 'name': 'ManRef DI AnlgLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1850', 'name': 'RefA TrmPct Sel', 'defaultValue': '101851', 'record': 'true', 'type': 'yA==' },
            { 'number': '1851', 'name': 'RefA TrmPct Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1852', 'name': 'RefA TrmPct AnHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1853', 'name': 'RefA TrmPct AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1855', 'name': 'RefA Trim Sel', 'defaultValue': '101856', 'record': 'true', 'type': 'yA==' },
            { 'number': '1856', 'name': 'RefA Trim Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1857', 'name': 'RefA Trim AnHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1858', 'name': 'RefA Trim AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1860', 'name': 'RefB TrmPct Sel', 'defaultValue': '101861', 'record': 'true', 'type': 'yA==' },
            { 'number': '1861', 'name': 'RefB TrmPct Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1862', 'name': 'RefB TrmPct AnHi', 'defaultValue': '100', 'record': 'true', 'type': 'yg==' },
            { 'number': '1863', 'name': 'RefB TrmPct AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1865', 'name': 'RefB Trim Sel', 'defaultValue': '101866', 'record': 'true', 'type': 'yA==' },
            { 'number': '1866', 'name': 'RefB Trim Stpt', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1867', 'name': 'RefB Trim AnHi', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1868', 'name': 'RefB Trim AnLo', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1870', 'name': 'VelTrimPctRefSrc', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '1871', 'name': 'Vel Trim Source', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '1890', 'name': 'VRef Sel Sts', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '1892', 'name': 'VRef Selected', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1894', 'name': 'Jog Speed 1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1895', 'name': 'Jog Speed 2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1896', 'name': 'Jog Acc Dec Time', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1898', 'name': 'Vel Limit Pos', 'defaultValue': '60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1899', 'name': 'Vel Limit Neg', 'defaultValue': '-60', 'record': 'true', 'type': 'yg==' },
            { 'number': '1900', 'name': 'Vel Low Lim Pos', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1901', 'name': 'Vel Low Lim Neg', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1903', 'name': 'AtSpeedTolerance', 'defaultValue': '0.59', 'record': 'true', 'type': 'yg==' },
            { 'number': '1904', 'name': 'Overspeed Limit', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1906', 'name': 'VRef Limited', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1908', 'name': 'Skip Speed 1', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1909', 'name': 'Skip Speed 2', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1910', 'name': 'Skip Speed 3', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1911', 'name': 'Skip Speed Band', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1914', 'name': 'VRef Commanded', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1915', 'name': 'VRef Accel Time1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1916', 'name': 'VRef Accel Time2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1917', 'name': 'VRef Decel Time1', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1918', 'name': 'VRef Decel Time2', 'defaultValue': '10', 'record': 'true', 'type': 'yg==' },
            { 'number': '1919', 'name': 'VRef Accel Jerk', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1920', 'name': 'VRef Decel Jerk', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '1921', 'name': 'Accel Limit Actn', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1922', 'name': 'Decel Limit Actn', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '1923', 'name': 'VRef Ramped', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1933', 'name': 'VRef Final', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '1950', 'name': 'Vel Ctrl Options', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '1961', 'name': 'Droop RPM at FLA', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' }
        ]";
    }
}
