namespace powerFlexBackup.cipdevice.PortCards
{
    /// <summary>
    /// PowerFlex 755TS Main Drive Controller
    ///
    /// PowerFlex 750 Series main drive at Port 0.
    /// ProductCode 7568 identifies the PowerFlex 755TS.
    ///
    /// 337 parameters (264 writable, 73 read-only).
    /// Types: yA== (0xC8 DINT), yg== (0xCA REAL), xg== (0xC6 INT), 0g== (0xD2 DWORD), 0w== (0xD3 LWORD)
    /// </summary>
    public class PF750_PortCard_PowerFlex755TS : PowerFlex750PortCard
    {
        public override ushort[] ProductCodes => [7568];
        public override string ProductName => "PowerFlex 755TS";
        public override int HostClassID => 0x9F;

        protected override string hostParameterListJSON => @"[
            { 'number': '1', 'name': 'Reserved', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '3', 'name': 'DC Bus Volts', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '5', 'name': 'Elapsed MWH', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '6', 'name': 'Elapsed kWH', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '7', 'name': 'Elapsed Run Time', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '8', 'name': 'Elpsd Mtr MWHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '9', 'name': 'Elpsd Rgn MWHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '10', 'name': 'Elpsd Mtr kWHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '11', 'name': 'Elpsd Rgn kWHrs', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '15', 'name': 'Average Power', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '25', 'name': 'Ctrl Pod Temp', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '26', 'name': 'DC Bus Trip OVRD', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '27', 'name': 'DCBusThreshUser', 'defaultValue': '814.7', 'record': 'true', 'type': 'yg==' },
            { 'number': '28', 'name': 'DCBusThresh Act', 'defaultValue': '815', 'record': 'false', 'type': 'yg==' },
            { 'number': '30', 'name': 'Access Level', 'defaultValue': '2', 'record': 'true', 'type': 'xg==' },
            { 'number': '31', 'name': 'Language', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '33', 'name': 'VoltageClass Cfg', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '34', 'name': 'VoltageClass Act', 'defaultValue': '1', 'record': 'false', 'type': 'yA==' },
            { 'number': '35', 'name': 'Duty Rating Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '36', 'name': 'Duty Rating Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '37', 'name': 'Prchrg Control', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '38', 'name': 'Prchrg Delay', 'defaultValue': '0.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '39', 'name': 'Prchrg Err Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '41', 'name': 'Logic Mask', 'defaultValue': '1100001001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '42', 'name': 'Auto Mask', 'defaultValue': '1100001001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '43', 'name': 'Manual Cmd Mask', 'defaultValue': '1100001001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '44', 'name': 'Manual Ref Mask', 'defaultValue': '1100001001111111', 'record': 'true', 'type': '0g==' },
            { 'number': '46', 'name': 'Velocity Units', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '47', 'name': 'Vel Units Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '52', 'name': 'Manual Preload', 'defaultValue': '0000000000000000', 'record': 'true', 'type': '0g==' },
            { 'number': '55', 'name': 'Reset Meters', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '56', 'name': 'RemMed EventActn', 'defaultValue': '1', 'record': 'true', 'type': 'yA==' },
            { 'number': '59', 'name': 'Energy Status', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '60', 'name': 'Auto Retry Fault', 'defaultValue': '0000000000000001', 'record': 'true', 'type': '0g==' },
            { 'number': '61', 'name': 'Auto Rstrt Tries', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '62', 'name': 'Auto Rstrt Delay', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '65', 'name': 'Pri MtrCtrl Mode', 'defaultValue': '2', 'record': 'true', 'type': 'yA==' },
            { 'number': '66', 'name': 'Pri MtrCtrl Act', 'defaultValue': '2', 'record': 'false', 'type': 'yA==' },
            { 'number': '67', 'name': 'Sec MtrCtrl Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '68', 'name': 'Sec MtrCtrl Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '70', 'name': 'Application Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '71', 'name': 'Application Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '72', 'name': 'Emb Logic Select', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '73', 'name': 'Emb Logic Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '74', 'name': 'Motor Ctrl Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '75', 'name': 'Mtr Ctrl Sel Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '83', 'name': 'TAM Option Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '84', 'name': 'Aux 24V Power', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '100', 'name': 'Digital In Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '101', 'name': 'Digital In Cfg', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '103', 'name': 'DI M Enable', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '108', 'name': 'DI M Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '109', 'name': 'DI M Stop Mode B', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '110', 'name': 'DI M CurLmt Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '111', 'name': 'DI M Coast Stop', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '114', 'name': 'DI Clear Fault', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '115', 'name': 'DI Aux Fault', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '117', 'name': 'DI M Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '118', 'name': 'DI M HOA Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '120', 'name': 'DI M Run', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '124', 'name': 'DI M Jog 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '127', 'name': 'DI M Jog 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '130', 'name': 'DI M Fwd Reverse', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '132', 'name': 'DI M Manual Ctrl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '134', 'name': 'DI EmergencyOVRD', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '135', 'name': 'DI Energy Pause', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '140', 'name': 'DI M Speed Sel 0', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '141', 'name': 'DI M Speed Sel 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '142', 'name': 'DI M Speed Sel 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '144', 'name': 'DI M Accel Time', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '145', 'name': 'DI M Decel Time', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '147', 'name': 'DI ManRef Sel', 'defaultValue': '215', 'record': 'true', 'type': 'yA==' },
            { 'number': '151', 'name': 'DI M MOP Inc', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '152', 'name': 'DI M MOP Dec', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '160', 'name': 'DI M SpTqPs Sel0', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '161', 'name': 'DI M SpTqPs Sel1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '163', 'name': 'DI M BusRegMode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '164', 'name': 'DI M PwrLossMode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '166', 'name': 'DI M Pwr Loss', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '167', 'name': 'DI M TorqueStptA', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '169', 'name': 'DI Mtr Ctrl Sel', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '170', 'name': 'DI Find Home', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '171', 'name': 'DI Return Home', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '172', 'name': 'DI Redefine Psn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '173', 'name': 'DI OL Home Limit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '176', 'name': 'DI Indx Step', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '177', 'name': 'DI Indx StepRev', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '178', 'name': 'DI Indx StepPrst', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '180', 'name': 'DI FwdEndLimit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '181', 'name': 'DI FwdDecLimit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '182', 'name': 'DI RevEndLimit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '183', 'name': 'DI RevDecLimit', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '184', 'name': 'DI PHw OvrTrvl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '185', 'name': 'DI NHw OvrTrvl', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '190', 'name': 'DI Precharge', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '191', 'name': 'DI Prchrg Seal', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '200', 'name': 'MS Logic Rslt', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '204', 'name': 'DPI Pt1 Flt Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '205', 'name': 'DPI Pt1 Flt Ref', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '206', 'name': 'DPI Pt2 Flt Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '207', 'name': 'DPI Pt2 Flt Ref', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '208', 'name': 'DPI Pt3 Flt Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '209', 'name': 'DPI Pt3 Flt Ref', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '211', 'name': 'Emb Enet Ref', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '214', 'name': 'Port 1 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '215', 'name': 'Port 2 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '216', 'name': 'Port 3 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '217', 'name': 'Port 4 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '218', 'name': 'Port 5 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '219', 'name': 'Port 6 Reference', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '221', 'name': 'Emb Logic Ref', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '230', 'name': 'Write Mask Cfg', 'defaultValue': '1000001111111110', 'record': 'true', 'type': '0g==' },
            { 'number': '231', 'name': 'Write Mask Act', 'defaultValue': '1000001111111110', 'record': 'false', 'type': '0g==' },
            { 'number': '232', 'name': 'Port Mask Cfg', 'defaultValue': '1000001111111110', 'record': 'true', 'type': '0g==' },
            { 'number': '233', 'name': 'Port Mask Act', 'defaultValue': '1000001111111110', 'record': 'false', 'type': '0g==' },
            { 'number': '260', 'name': 'Stop Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '261', 'name': 'Start Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '262', 'name': 'Jog Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '263', 'name': 'Dir Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '264', 'name': 'Clear Flt Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '265', 'name': 'Manual Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '266', 'name': 'Ref Select Owner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '267', 'name': 'EnergyPauseOwner', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '300', 'name': 'Net Addr Sel', 'defaultValue': '3', 'record': 'true', 'type': 'yA==' },
            { 'number': '301', 'name': 'Net Addr Src', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '302', 'name': 'IP Addr Cfg 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '303', 'name': 'IP Addr Cfg 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '304', 'name': 'IP Addr Cfg 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '305', 'name': 'IP Addr Cfg 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '306', 'name': 'Subnet Cfg 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '307', 'name': 'Subnet Cfg 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '308', 'name': 'Subnet Cfg 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '309', 'name': 'Subnet Cfg 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '310', 'name': 'Gateway Cfg 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '311', 'name': 'Gateway Cfg 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '312', 'name': 'Gateway Cfg 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '313', 'name': 'Gateway Cfg 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '314', 'name': 'Net Rate Cfg 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '315', 'name': 'Net Rate Act 1', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '316', 'name': 'Net Rate Cfg 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '317', 'name': 'Net Rate Act 2', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '321', 'name': 'DL From Net 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '322', 'name': 'DL From Net 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '323', 'name': 'DL From Net 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '324', 'name': 'DL From Net 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '325', 'name': 'DL From Net 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '326', 'name': 'DL From Net 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '327', 'name': 'DL From Net 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '328', 'name': 'DL From Net 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '329', 'name': 'DL From Net 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '330', 'name': 'DL From Net 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '331', 'name': 'DL From Net 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '332', 'name': 'DL From Net 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '333', 'name': 'DL From Net 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '334', 'name': 'DL From Net 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '335', 'name': 'DL From Net 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '336', 'name': 'DL From Net 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '340', 'name': 'DL To Net 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '341', 'name': 'DL To Net 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '342', 'name': 'DL To Net 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '343', 'name': 'DL To Net 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '344', 'name': 'DL To Net 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '345', 'name': 'DL To Net 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '346', 'name': 'DL To Net 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '347', 'name': 'DL To Net 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '348', 'name': 'DL To Net 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '349', 'name': 'DL To Net 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '350', 'name': 'DL To Net 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '351', 'name': 'DL To Net 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '352', 'name': 'DL To Net 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '353', 'name': 'DL To Net 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '354', 'name': 'DL To Net 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '355', 'name': 'DL To Net 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '356', 'name': 'DLs From Net Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '357', 'name': 'DLs To Net Act', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '360', 'name': 'Comm Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '361', 'name': 'Idle Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '363', 'name': 'Msg Flt Action', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '364', 'name': 'Flt Cfg Logic', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '365', 'name': 'Flt Cfg Ref', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '370', 'name': 'Flt Cfg DL 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '371', 'name': 'Flt Cfg DL 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '372', 'name': 'Flt Cfg DL 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '373', 'name': 'Flt Cfg DL 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '374', 'name': 'Flt Cfg DL 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '375', 'name': 'Flt Cfg DL 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '376', 'name': 'Flt Cfg DL 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '377', 'name': 'Flt Cfg DL 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '378', 'name': 'Flt Cfg DL 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '379', 'name': 'Flt Cfg DL 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '380', 'name': 'Flt Cfg DL 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '381', 'name': 'Flt Cfg DL 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '382', 'name': 'Flt Cfg DL 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '383', 'name': 'Flt Cfg DL 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '384', 'name': 'Flt Cfg DL 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '385', 'name': 'Flt Cfg DL 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '420', 'name': 'M Gnd Warn Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '421', 'name': 'M Gnd Warn Lvl', 'defaultValue': '4', 'record': 'true', 'type': 'yg==' },
            { 'number': '425', 'name': 'HRG GF Flt Actn', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '426', 'name': 'HRG GF Thresh', 'defaultValue': '0.5', 'record': 'true', 'type': 'yg==' },
            { 'number': '427', 'name': 'HRG GF Freq', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '428', 'name': 'HRG GF Neut Vltg', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '429', 'name': 'HRG GF Pk Vltg', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '454', 'name': 'Emerg OVRD Mode', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '455', 'name': 'Emerg Prot OVRD', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '456', 'name': 'EmergMode Status', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '457', 'name': 'Purge Frequency', 'defaultValue': '15', 'record': 'true', 'type': 'yg==' },
            { 'number': '600', 'name': 'Safety Port Sts', 'defaultValue': '0000000000000000', 'record': 'false', 'type': '0g==' },
            { 'number': '603', 'name': 'Start Inhibits', 'defaultValue': '00000000000000000000000000000000', 'record': 'false', 'type': '0w==' },
            { 'number': '604', 'name': 'M Last Stop Src', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '606', 'name': 'M Last StartSrc', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '610', 'name': 'Last Fault Code', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '700', 'name': 'UserData Int 00', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '701', 'name': 'UserData Int 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '702', 'name': 'UserData Int 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '703', 'name': 'UserData Int 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '704', 'name': 'UserData Int 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '705', 'name': 'UserData Int 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '706', 'name': 'UserData Int 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '707', 'name': 'UserData Int 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '708', 'name': 'UserData Int 08', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '709', 'name': 'UserData Int 09', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '710', 'name': 'UserData Int 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '711', 'name': 'UserData Int 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '712', 'name': 'UserData Int 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '713', 'name': 'UserData Int 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '714', 'name': 'UserData Int 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '715', 'name': 'UserData Int 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '716', 'name': 'UserData Int 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '717', 'name': 'UserData Int 17', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '718', 'name': 'UserData Int 18', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '719', 'name': 'UserData Int 19', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '720', 'name': 'UserData Int 20', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '721', 'name': 'UserData Int 21', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '722', 'name': 'UserData Int 22', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '723', 'name': 'UserData Int 23', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '724', 'name': 'UserData Int 24', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '725', 'name': 'UserData Int 25', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '726', 'name': 'UserData Int 26', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '727', 'name': 'UserData Int 27', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '728', 'name': 'UserData Int 28', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '729', 'name': 'UserData Int 29', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '730', 'name': 'UserData Int 30', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '731', 'name': 'UserData Int 31', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '800', 'name': 'UserData Real 00', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '801', 'name': 'UserData Real 01', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '802', 'name': 'UserData Real 02', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '803', 'name': 'UserData Real 03', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '804', 'name': 'UserData Real 04', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '805', 'name': 'UserData Real 05', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '806', 'name': 'UserData Real 06', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '807', 'name': 'UserData Real 07', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '808', 'name': 'UserData Real 08', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '809', 'name': 'UserData Real 09', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '810', 'name': 'UserData Real 10', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '811', 'name': 'UserData Real 11', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '812', 'name': 'UserData Real 12', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '813', 'name': 'UserData Real 13', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '814', 'name': 'UserData Real 14', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '815', 'name': 'UserData Real 15', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '816', 'name': 'UserData Real 16', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '817', 'name': 'UserData Real 17', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '818', 'name': 'UserData Real 18', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '819', 'name': 'UserData Real 19', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '820', 'name': 'UserData Real 20', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '821', 'name': 'UserData Real 21', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '822', 'name': 'UserData Real 22', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '823', 'name': 'UserData Real 23', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '824', 'name': 'UserData Real 24', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '825', 'name': 'UserData Real 25', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '826', 'name': 'UserData Real 26', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '827', 'name': 'UserData Real 27', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '828', 'name': 'UserData Real 28', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '829', 'name': 'UserData Real 29', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '830', 'name': 'UserData Real 30', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '831', 'name': 'UserData Real 31', 'defaultValue': '0', 'record': 'true', 'type': 'yg==' },
            { 'number': '850', 'name': 'Prof DI Invert', 'defaultValue': '00000000000000000000000000000000', 'record': 'true', 'type': '0w==' },
            { 'number': '851', 'name': 'DI Hold Step', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '852', 'name': 'DI Abort Step', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '853', 'name': 'DI Abort Profile', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '854', 'name': 'DI Vel Override', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '855', 'name': 'DI StrtStep Sel0', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '856', 'name': 'DI StrtStep Sel1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '857', 'name': 'DI StrtStep Sel2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '858', 'name': 'DI StrtStep Sel3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '859', 'name': 'DI StrtStep Sel4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '860', 'name': 'DI Step 1', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '861', 'name': 'DI Step 2', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '862', 'name': 'DI Step 3', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '863', 'name': 'DI Step 4', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '864', 'name': 'DI Step 5', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '865', 'name': 'DI Step 6', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '866', 'name': 'DI Step 7', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '867', 'name': 'DI Step 8', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '868', 'name': 'DI Step 9', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '869', 'name': 'DI Step 10', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '870', 'name': 'DI Step 11', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '871', 'name': 'DI Step 12', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '872', 'name': 'DI Step 13', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '873', 'name': 'DI Step 14', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '874', 'name': 'DI Step 15', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '875', 'name': 'DI Step 16', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '880', 'name': 'DI PCAM Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '883', 'name': 'DI VCAM Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '886', 'name': 'DI TqCAM Start', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '900', 'name': 'ScaleBlk Sel 00', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '901', 'name': 'ScaleBlk Scal 00', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '902', 'name': 'ScaleBlk Int 00', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '903', 'name': 'ScaleBlk Real 00', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '904', 'name': 'ScaleBlk Sel 01', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '905', 'name': 'ScaleBlk Scal 01', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '906', 'name': 'ScaleBlk Int 01', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '907', 'name': 'ScaleBlk Real 01', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '908', 'name': 'ScaleBlk Sel 02', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '909', 'name': 'ScaleBlk Scal 02', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '910', 'name': 'ScaleBlk Int 02', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '911', 'name': 'ScaleBlk Real 02', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '912', 'name': 'ScaleBlk Sel 03', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '913', 'name': 'ScaleBlk Scal 03', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '914', 'name': 'ScaleBlk Int 03', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '915', 'name': 'ScaleBlk Real 03', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '916', 'name': 'ScaleBlk Sel 04', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '917', 'name': 'ScaleBlk Scal 04', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '918', 'name': 'ScaleBlk Int 04', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '919', 'name': 'ScaleBlk Real 04', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '920', 'name': 'ScaleBlk Sel 05', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '921', 'name': 'ScaleBlk Scal 05', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '922', 'name': 'ScaleBlk Int 05', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '923', 'name': 'ScaleBlk Real 05', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '924', 'name': 'ScaleBlk Sel 06', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '925', 'name': 'ScaleBlk Scal 06', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '926', 'name': 'ScaleBlk Int 06', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '927', 'name': 'ScaleBlk Real 06', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' },
            { 'number': '928', 'name': 'ScaleBlk Sel 07', 'defaultValue': '0', 'record': 'true', 'type': 'yA==' },
            { 'number': '929', 'name': 'ScaleBlk Scal 07', 'defaultValue': '1', 'record': 'true', 'type': 'yg==' },
            { 'number': '930', 'name': 'ScaleBlk Int 07', 'defaultValue': '0', 'record': 'false', 'type': 'yA==' },
            { 'number': '931', 'name': 'ScaleBlk Real 07', 'defaultValue': '0', 'record': 'false', 'type': 'yg==' }
        ]";
    }
}
